use crate::codegen;
use crate::manifest::SchemaRegistry;
use crate::paths;
use crate::resolve;
use crate::validate;
use anyhow::{bail, Context, Result};
use std::path::Path;

pub fn run(repo_root: &Path) -> Result<()> {
    let registry = SchemaRegistry::load(repo_root)?;
    resolve::check_all_refs(&registry)?;
    validate_schema_documents(&registry)?;

    // Generation drift check (read-only).
    let expected_types = codegen::generate_rust_module(&registry)?;
    let expected_catalog = codegen::generate_catalog_module(&registry)?;
    let expected_typed = codegen::generate_typed_module(&registry)?;
    let expected_mod = "\
// @generated by schema-tool. DO NOT EDIT BY HAND.
// GENERATED module root for kernel-contracts.

//! Auto-generated contract types from `schemas/source`.

mod catalog;
mod typed;
mod types;

pub use catalog::*;
pub use typed::*;
pub use types::*;
";
    let generated_dir = paths::generated_dir(repo_root);
    let types_path = generated_dir.join("types.rs");
    let catalog_path = generated_dir.join("catalog.rs");
    let typed_path = generated_dir.join("typed.rs");
    let mod_path = generated_dir.join("mod.rs");

    if !types_path.is_file()
        || !catalog_path.is_file()
        || !typed_path.is_file()
        || !mod_path.is_file()
    {
        bail!(
            "generated files missing under {}; run `schema-tool generate`",
            generated_dir.display()
        );
    }

    let actual_types = std::fs::read_to_string(&types_path)
        .with_context(|| format!("read {}", types_path.display()))?;
    let actual_catalog = std::fs::read_to_string(&catalog_path)
        .with_context(|| format!("read {}", catalog_path.display()))?;
    let actual_typed = std::fs::read_to_string(&typed_path)
        .with_context(|| format!("read {}", typed_path.display()))?;
    let actual_mod = std::fs::read_to_string(&mod_path)
        .with_context(|| format!("read {}", mod_path.display()))?;

    let expected_types = ensure_trailing_newline(&expected_types);
    let expected_catalog = ensure_trailing_newline(&expected_catalog);
    let expected_typed = ensure_trailing_newline(&expected_typed);
    let expected_mod = ensure_trailing_newline(expected_mod);

    if actual_types != expected_types {
        bail!("generation drift in {}", types_path.display());
    }
    if actual_catalog != expected_catalog {
        bail!("generation drift in {}", catalog_path.display());
    }
    if actual_typed != expected_typed {
        bail!("generation drift in {}", typed_path.display());
    }
    if actual_mod != expected_mod {
        bail!("generation drift in {}", mod_path.display());
    }

    // Validate examples if present.
    let examples = paths::examples_dir(repo_root);
    if examples.is_dir() {
        validate::validate_examples(repo_root, &registry, &examples)?;
    }

    println!(
        "schema-tool check ok: {} schemas, Draft 2020-12 meta-validation, refs, catalog and generated types stable",
        registry.manifest.schemas.len()
    );
    Ok(())
}

fn validate_schema_documents(registry: &SchemaRegistry) -> Result<()> {
    for (id, loaded) in &registry.by_id {
        jsonschema::draft202012::meta::validate(&loaded.document).map_err(|error| {
            anyhow::anyhow!("schema {id} fails Draft 2020-12 meta-schema: {error}")
        })?;
    }
    validate::compile_all(registry)
        .map_err(|error| anyhow::anyhow!("Draft 2020-12 schema compilation failed: {error}"))?;
    Ok(())
}

fn ensure_trailing_newline(content: &str) -> String {
    format!("{}\n", content.trim_end_matches(['\r', '\n']))
}
