//! Restricted deterministic Rust type generator from JSON Schema 2020-12 sources.
//!
//! Shape support is intentionally closed. Validation-only keywords remain in the source
//! schemas and are enforced by the runtime JSON Schema validator.

use crate::error::SchemaToolError;
use crate::manifest::{LoadedSchema, SchemaRegistry};
use crate::resolve::resolve_ref;
use anyhow::Result;
use serde_json::Value;
use std::collections::{BTreeMap, BTreeSet};

const GENERATED_HEADER: &str = "\
// @generated by schema-tool. DO NOT EDIT BY HAND.
// GENERATED from schemas/source via deterministic restricted codegen.
// Source of truth: JSON Schema Draft 2020-12 under schemas/source/.
";

#[derive(Debug, Clone)]
enum RustType {
    NullOnly,
    Bool,
    I64,
    F64,
    String,
    JsonValue,
    Option(Box<RustType>),
    Vec(Box<RustType>),
    Named(String),
}

#[derive(Debug, Clone)]
struct StructField {
    json_name: String,
    rust_name: String,
    ty: RustType,
    required: bool,
    /// Whether the Schema property type itself accepts JSON null.
    ///
    /// Optional non-null fields serialize with omission (`skip_serializing_if`), while
    /// nullable fields keep explicit `null` so required-nullable contracts stay intact.
    allows_null: bool,
}

#[derive(Debug, Default)]
struct TypeCollector {
    defs: BTreeMap<String, String>,
    emitted_names: BTreeSet<String>,
    pending_ids: BTreeSet<String>,
    done_ids: BTreeSet<String>,
    id_to_name: BTreeMap<String, String>,
}

pub fn generate_rust_module(registry: &SchemaRegistry) -> Result<String> {
    let mut collector = TypeCollector::default();
    for entry in &registry.manifest.schemas {
        let loaded = registry.get(&entry.id)?;
        audit_schema_tree(&loaded.document, &entry.id)?;
        collector
            .id_to_name
            .insert(entry.id.clone(), rust_type_name_for_schema(loaded));
        collector.pending_ids.insert(entry.id.clone());
    }

    while let Some(id) = collector.pending_ids.iter().next().cloned() {
        collector.pending_ids.remove(&id);
        if collector.done_ids.insert(id.clone()) {
            emit_named_schema(registry, &mut collector, registry.get(&id)?)?;
        }
    }

    let mut out = String::from(GENERATED_HEADER);
    out.push_str("\n#![cfg_attr(rustfmt, rustfmt::skip)]\n");
    out.push_str("#![allow(clippy::all)]\n#![allow(dead_code)]\n#![allow(unused_imports)]\n\n");
    out.push_str("use serde::{Deserialize, Deserializer, Serialize, Serializer};\n");
    out.push_str("use serde::de::Error as DeError;\n");
    out.push_str("use serde_json::Value as JsonValue;\n\n");
    out.push_str(render_null_only());
    out.push('\n');

    for body in collector.defs.values() {
        out.push_str(body);
        if !body.ends_with('\n') {
            out.push('\n');
        }
        out.push('\n');
    }
    Ok(out)
}

#[derive(Debug, Clone)]
struct PayloadBinding {
    discriminator_value: String,
    variant_name: String,
    payload_type: String,
}

#[derive(Debug, Clone)]
struct EnvelopeBinding {
    schema_id: String,
    title: String,
    discriminator: String,
    payload_enum_name: String,
    typed_name: String,
    raw_name: String,
    mappings: Vec<PayloadBinding>,
}

pub fn generate_typed_module(registry: &SchemaRegistry) -> Result<String> {
    let bindings = discover_typed_envelopes(registry)?;
    if bindings.is_empty() {
        return Err(SchemaToolError::msg(
            "no conditional envelope payload bindings found in manifest schemas",
        )
        .into());
    }

    let mut rendered = Vec::new();
    let mut imports = BTreeSet::new();
    for binding in &bindings {
        rendered.push(render_typed_envelope(registry, binding, &mut imports)?);
    }

    let mut out = String::from(GENERATED_HEADER);
    out.push_str("\n#![cfg_attr(rustfmt, rustfmt::skip)]\n");
    out.push_str("#![allow(clippy::all)]\n\n");
    out.push_str(
        "//! Typed envelope decoding derived from conditional JSON Schema payload mappings.\n\n",
    );
    out.push_str("use crate::error::ContractError;\n");
    out.push_str("use crate::validator::validate_json;\n");
    if !imports.is_empty() {
        out.push_str("use super::types::{\n");
        for name in imports {
            out.push_str(&format!("    {name},\n"));
        }
        out.push_str("};\n");
    }
    out.push_str("use serde::Deserialize;\n");
    out.push_str("use serde_json::Value;\n\n");
    for body in rendered {
        out.push_str(&body);
        if !body.ends_with('\n') {
            out.push('\n');
        }
        out.push('\n');
    }
    out.push_str(render_typed_decode_helpers());
    Ok(out)
}

pub fn generate_catalog_module(registry: &SchemaRegistry) -> Result<String> {
    let mut out = String::from(GENERATED_HEADER);
    out.push_str("\n#![cfg_attr(rustfmt, rustfmt::skip)]\n\n");
    out.push_str("/// Embedded schema documents generated from schemas/manifest.json.\n");
    out.push_str("pub const EMBEDDED_SCHEMA_DOCUMENTS: &[(&str, &str)] = &[\n");
    for entry in &registry.manifest.schemas {
        let include_path = format!("../../../../../{}", entry.source);
        out.push_str(&format!(
            "    ({:?}, include_str!({:?})),\n",
            entry.id, include_path
        ));
    }
    out.push_str("];\n\n");

    let commands = envelope_discriminators(registry, "command_envelope.json", "command_type")?;
    let queries = envelope_discriminators(registry, "query_envelope.json", "query_type")?;
    let events = envelope_discriminators(registry, "event_envelope.json", "type")?;
    let mut methods = commands.clone();
    methods.extend(queries.iter().cloned());
    methods.sort();

    render_str_slice(&mut out, "KCP_COMMAND_METHODS", &commands);
    render_str_slice(&mut out, "KCP_QUERY_METHODS", &queries);
    render_str_slice(&mut out, "KCP_V1_METHODS", &methods);
    render_str_slice(&mut out, "EVENT_V1_TYPES", &events);
    out.push_str("pub const KCP_PROTOCOL_VERSION: &str = \"1.0\";\n");
    Ok(out)
}

fn emit_named_schema(
    registry: &SchemaRegistry,
    collector: &mut TypeCollector,
    loaded: &LoadedSchema,
) -> Result<()> {
    let type_name = collector
        .id_to_name
        .get(&loaded.entry.id)
        .cloned()
        .unwrap_or_else(|| rust_type_name_for_schema(loaded));
    let doc = &loaded.document;
    validate_supported_schema_node(doc, &loaded.entry.id)?;

    if is_string_enum(doc) {
        emit_string_enum(collector, &type_name, &loaded.entry.id, doc)?;
    } else if is_nullable_string_enum(doc) {
        return Err(unsupported(
            "enum",
            &loaded.entry.id,
            "top-level nullable enum requires an explicit wrapper schema",
        ));
    } else if is_object_schema(doc) {
        emit_struct_from_schema(registry, collector, &type_name, &loaded.entry.id, doc)?;
    } else if doc.get("oneOf").is_some() {
        return Err(unsupported(
            "oneOf",
            &loaded.entry.id,
            "top-level non-nullable oneOf is ambiguous",
        ));
    } else {
        return Err(unsupported(
            "type",
            &loaded.entry.id,
            "top-level schema must be an object or string enum",
        ));
    }
    Ok(())
}

fn emit_struct_from_schema(
    registry: &SchemaRegistry,
    collector: &mut TypeCollector,
    type_name: &str,
    schema_id: &str,
    schema: &Value,
) -> Result<()> {
    if !collector.emitted_names.insert(type_name.to_string()) {
        return Ok(());
    }
    validate_supported_schema_node(schema, schema_id)?;

    let properties = schema
        .get("properties")
        .and_then(Value::as_object)
        .cloned()
        .unwrap_or_default();
    let required = required_set(schema);

    let mut names: Vec<_> = properties.keys().cloned().collect();
    names.sort();
    let mut fields = Vec::new();
    for json_name in names {
        let property = properties
            .get(&json_name)
            .ok_or_else(|| SchemaToolError::msg(format!("missing property {json_name}")))?;
        let hint = format!("{type_name}{}", to_pascal_case(&json_name));
        fields.push(StructField {
            rust_name: to_snake_case(&json_name),
            required: required.contains(&json_name),
            allows_null: schema_allows_null(registry, schema_id, property)?,
            ty: schema_to_type(registry, collector, schema_id, property, &hint)?,
            json_name,
        });
    }
    collector.defs.insert(
        type_name.to_string(),
        render_struct(type_name, schema_id, &fields),
    );
    Ok(())
}

fn schema_to_type(
    registry: &SchemaRegistry,
    collector: &mut TypeCollector,
    base_id: &str,
    schema: &Value,
    hint_name: &str,
) -> Result<RustType> {
    if schema == &Value::Bool(true) {
        return Ok(RustType::JsonValue);
    }
    if schema == &Value::Bool(false) {
        return Err(unsupported(
            "schema",
            base_id,
            "false schema has no inhabited Rust type",
        ));
    }
    validate_supported_schema_node(schema, base_id)?;

    if schema.get("$ref").is_some() {
        ensure_ref_has_only_annotation_siblings(schema, base_id)?;
    }

    if let Some(reference) = schema.get("$ref").and_then(Value::as_str) {
        let (resolved_id, resolved_schema) = resolve_ref(registry, base_id, reference)?;
        if reference.contains('#') && !reference.ends_with('#') {
            return schema_to_named_fragment(
                registry,
                collector,
                &resolved_id,
                &resolved_schema,
                hint_name,
            );
        }
        let name = collector
            .id_to_name
            .get(&resolved_id)
            .cloned()
            .unwrap_or_else(|| rust_type_name_from_id(&resolved_id));
        collector
            .id_to_name
            .insert(resolved_id.clone(), name.clone());
        collector.pending_ids.insert(resolved_id);
        return Ok(RustType::Named(name));
    }

    if let Some(variants) = schema.get("oneOf").and_then(Value::as_array) {
        return nullable_one_of(registry, collector, base_id, variants, hint_name);
    }

    if let Some(value) = schema.get("const") {
        ensure_const_matches_type(schema, value, base_id)?;
        emit_const_type(collector, hint_name, base_id, value)?;
        return Ok(RustType::Named(hint_name.to_string()));
    }

    if schema.get("properties").is_some() {
        emit_struct_from_schema(registry, collector, hint_name, base_id, schema)?;
        let named = RustType::Named(hint_name.to_string());
        return Ok(
            if schema
                .get("type")
                .and_then(Value::as_array)
                .is_some_and(|kinds| kinds.iter().any(|value| value == "null"))
            {
                RustType::Option(Box::new(named))
            } else {
                named
            },
        );
    }

    if is_nullable_string_enum(schema) {
        let values = string_enum_values(schema)?;
        emit_string_enum_values(collector, hint_name, base_id, &values)?;
        return Ok(RustType::Option(Box::new(RustType::Named(
            hint_name.to_string(),
        ))));
    }

    if is_string_enum(schema) {
        emit_string_enum(collector, hint_name, base_id, schema)?;
        return Ok(RustType::Named(hint_name.to_string()));
    }

    match schema.get("type") {
        Some(Value::String(kind)) => {
            primitive_or_container(registry, collector, base_id, schema, kind, hint_name)
        }
        Some(Value::Array(kinds)) => {
            let names: Vec<&str> = kinds.iter().filter_map(Value::as_str).collect();
            if names.len() != kinds.len() {
                return Err(unsupported(
                    "type",
                    base_id,
                    "type union contains a non-string member",
                ));
            }
            let non_null: Vec<&str> = names
                .iter()
                .copied()
                .filter(|name| *name != "null")
                .collect();
            if names.contains(&"null") && non_null.len() == 1 && names.len() == 2 {
                let inner = primitive_or_container(
                    registry,
                    collector,
                    base_id,
                    schema,
                    non_null[0],
                    hint_name,
                )?;
                Ok(RustType::Option(Box::new(inner)))
            } else {
                Err(unsupported(
                    "type",
                    base_id,
                    "only a single non-null type unioned with null is supported",
                ))
            }
        }
        None if schema.get("properties").is_some() => {
            emit_struct_from_schema(registry, collector, hint_name, base_id, schema)?;
            Ok(RustType::Named(hint_name.to_string()))
        }
        None => Err(unsupported(
            "type",
            base_id,
            "schema without type/$ref/enum/const is not a supported shape",
        )),
        Some(other) => Err(unsupported(
            "type",
            base_id,
            &format!("unsupported type form: {other}"),
        )),
    }
}

fn primitive_or_container(
    registry: &SchemaRegistry,
    collector: &mut TypeCollector,
    base_id: &str,
    schema: &Value,
    type_name: &str,
    hint_name: &str,
) -> Result<RustType> {
    match type_name {
        "null" => Ok(RustType::NullOnly),
        "boolean" => Ok(RustType::Bool),
        "integer" => Ok(RustType::I64),
        "number" => Ok(RustType::F64),
        "string" => Ok(RustType::String),
        "array" => {
            let items = schema.get("items").ok_or_else(|| {
                SchemaToolError::msg(format!("array without items in {base_id}/{hint_name}"))
            })?;
            Ok(RustType::Vec(Box::new(schema_to_type(
                registry,
                collector,
                base_id,
                items,
                &format!("{hint_name}Item"),
            )?)))
        }
        "object" if schema.get("properties").is_some() => {
            emit_struct_from_schema(registry, collector, hint_name, base_id, schema)?;
            Ok(RustType::Named(hint_name.to_string()))
        }
        "object" if schema.get("additionalProperties") == Some(&Value::Bool(true)) => {
            Ok(RustType::JsonValue)
        }
        "object" => Err(unsupported(
            "additionalProperties",
            base_id,
            "free-form object requires explicit additionalProperties: true",
        )),
        other => Err(unsupported(
            "type",
            base_id,
            &format!("unsupported type `{other}`"),
        )),
    }
}

fn schema_to_named_fragment(
    registry: &SchemaRegistry,
    collector: &mut TypeCollector,
    resolved_id: &str,
    schema: &Value,
    hint_name: &str,
) -> Result<RustType> {
    if is_string_enum(schema) {
        emit_string_enum(collector, hint_name, resolved_id, schema)?;
        Ok(RustType::Named(hint_name.to_string()))
    } else if is_object_schema(schema) {
        emit_struct_from_schema(registry, collector, hint_name, resolved_id, schema)?;
        Ok(RustType::Named(hint_name.to_string()))
    } else {
        schema_to_type(registry, collector, resolved_id, schema, hint_name)
    }
}

fn nullable_one_of(
    registry: &SchemaRegistry,
    collector: &mut TypeCollector,
    base_id: &str,
    variants: &[Value],
    hint_name: &str,
) -> Result<RustType> {
    if variants.len() != 2 {
        return Err(unsupported(
            "oneOf",
            base_id,
            "only nullable oneOf with exactly [null, T] is supported",
        ));
    }
    let non_null: Vec<&Value> = variants
        .iter()
        .filter(|value| !is_null_type(value))
        .collect();
    if non_null.len() != 1 || !variants.iter().any(is_null_type) {
        return Err(unsupported(
            "oneOf",
            base_id,
            "ambiguous oneOf requires an explicit generated discriminator strategy",
        ));
    }
    Ok(RustType::Option(Box::new(schema_to_type(
        registry,
        collector,
        base_id,
        non_null[0],
        hint_name,
    )?)))
}

fn emit_string_enum(
    collector: &mut TypeCollector,
    name: &str,
    schema_id: &str,
    schema: &Value,
) -> Result<()> {
    emit_string_enum_values(collector, name, schema_id, &string_enum_values(schema)?)
}

fn emit_string_enum_values(
    collector: &mut TypeCollector,
    name: &str,
    schema_id: &str,
    values: &[String],
) -> Result<()> {
    if collector.emitted_names.insert(name.to_string()) {
        collector.defs.insert(
            name.to_string(),
            render_string_enum(name, schema_id, values),
        );
    }
    Ok(())
}

fn render_struct(type_name: &str, schema_id: &str, fields: &[StructField]) -> String {
    let mut body = format!(
        "/// Generated from `{schema_id}`\n#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]\n#[serde(deny_unknown_fields)]\npub struct {type_name} {{\n"
    );
    for field in fields {
        let mut ty = field.ty.clone();
        if !field.required {
            ty = match ty {
                RustType::Option(_) => ty,
                other => RustType::Option(Box::new(other)),
            };
        }
        let mut serde_attrs = Vec::new();
        if field.rust_name != field.json_name {
            serde_attrs.push(format!("rename = {:?}", field.json_name));
        }
        // required=false && allows_null=false => omit None; do not invent null on the wire.
        // required nullable and optional nullable keep explicit null (no skip).
        if !field.required && !field.allows_null {
            serde_attrs.push("skip_serializing_if = \"Option::is_none\"".to_string());
        }
        if !serde_attrs.is_empty() {
            body.push_str(&format!("    #[serde({})]\n", serde_attrs.join(", ")));
        }
        let rendered = render_type_ref(&ty);
        body.push_str(&format!("    pub {}: {},\n", field.rust_name, rendered));
    }
    body.push_str("}\n");
    body
}

fn render_type_ref(ty: &RustType) -> String {
    match ty {
        RustType::NullOnly => "NullOnly".into(),
        RustType::Bool => "bool".into(),
        RustType::I64 => "i64".into(),
        RustType::F64 => "f64".into(),
        RustType::String => "String".into(),
        RustType::JsonValue => "JsonValue".into(),
        RustType::Option(inner) => format!("Option<{}>", render_type_ref(inner)),
        RustType::Vec(inner) => format!("Vec<{}>", render_type_ref(inner)),
        RustType::Named(name) => name.clone(),
    }
}

fn emit_const_type(
    collector: &mut TypeCollector,
    name: &str,
    schema_id: &str,
    value: &Value,
) -> Result<()> {
    if !collector.emitted_names.insert(name.to_string()) {
        return Ok(());
    }
    let body = match value {
        Value::String(expected) => format!(
            "/// Generated string const from `{schema_id}`\n#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]\npub enum {name} {{\n    #[serde(rename = {:?})]\n    Value,\n}}\n",
            expected
        ),
        Value::Number(number) if number.is_i64() => {
            let expected = number.to_string();
            format!(
                "/// Generated integer const from `{schema_id}`\n#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]\npub struct {name};\nimpl Serialize for {name} {{ fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error> where S: Serializer {{ serializer.serialize_i64({expected}) }} }}\nimpl<'de> Deserialize<'de> for {name} {{ fn deserialize<D>(deserializer: D) -> Result<Self, D::Error> where D: Deserializer<'de> {{ let value = i64::deserialize(deserializer)?; if value == {expected} {{ Ok(Self) }} else {{ Err(D::Error::custom(format!(\"expected integer const {expected}, got {{value}}\"))) }} }} }}\n"
            )
        }
        Value::Number(number) if number.is_u64() => {
            let expected = number.to_string();
            format!(
                "/// Generated integer const from `{schema_id}`\n#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]\npub struct {name};\nimpl Serialize for {name} {{ fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error> where S: Serializer {{ serializer.serialize_u64({expected}) }} }}\nimpl<'de> Deserialize<'de> for {name} {{ fn deserialize<D>(deserializer: D) -> Result<Self, D::Error> where D: Deserializer<'de> {{ let value = u64::deserialize(deserializer)?; if value == {expected} {{ Ok(Self) }} else {{ Err(D::Error::custom(format!(\"expected integer const {expected}, got {{value}}\"))) }} }} }}\n"
            )
        }
        Value::Bool(expected) => format!(
            "/// Generated boolean const from `{schema_id}`\n#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]\npub struct {name};\nimpl Serialize for {name} {{ fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error> where S: Serializer {{ serializer.serialize_bool({expected}) }} }}\nimpl<'de> Deserialize<'de> for {name} {{ fn deserialize<D>(deserializer: D) -> Result<Self, D::Error> where D: Deserializer<'de> {{ let value = bool::deserialize(deserializer)?; if value == {expected} {{ Ok(Self) }} else {{ Err(D::Error::custom(format!(\"expected boolean const {expected}, got {{value}}\"))) }} }} }}\n"
        ),
        Value::Null => render_null_only().replace("NullOnly", name),
        _ => {
            return Err(unsupported(
                "const",
                schema_id,
                "only string, integer, boolean, and null const values are supported",
            ))
        }
    };
    collector.defs.insert(name.to_string(), body);
    Ok(())
}

fn render_string_enum(type_name: &str, schema_id: &str, values: &[String]) -> String {
    let mut body = format!(
        "/// Generated string enum from `{schema_id}`\n#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]\npub enum {type_name} {{\n"
    );
    for value in values {
        body.push_str(&format!(
            "    #[serde(rename = {:?})]\n    {},\n",
            value,
            to_enum_variant(value)
        ));
    }
    body.push_str("}\n");
    body.push_str(&format!("\nimpl {type_name} {{\n    pub fn as_str(self) -> &'static str {{\n        match self {{\n"));
    for value in values {
        body.push_str(&format!(
            "            Self::{} => {:?},\n",
            to_enum_variant(value),
            value
        ));
    }
    body.push_str("        }\n    }\n}\n");
    body
}

fn render_null_only() -> &'static str {
    "/// JSON null and no other value.\n#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]\npub struct NullOnly;\nimpl Serialize for NullOnly { fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error> where S: Serializer { serializer.serialize_none() } }\nimpl<'de> Deserialize<'de> for NullOnly { fn deserialize<D>(deserializer: D) -> Result<Self, D::Error> where D: Deserializer<'de> { <()>::deserialize(deserializer).map(|()| Self) } }\n"
}

fn render_str_slice(out: &mut String, name: &str, values: &[String]) {
    out.push_str(&format!("pub const {name}: &[&str] = &[\n"));
    for value in values {
        out.push_str(&format!("    {:?},\n", value));
    }
    out.push_str("];\n\n");
}

fn discover_typed_envelopes(registry: &SchemaRegistry) -> Result<Vec<EnvelopeBinding>> {
    let mut bindings = Vec::new();
    for entry in &registry.manifest.schemas {
        if entry.kind != "envelope" {
            continue;
        }
        let loaded = registry.get(&entry.id)?;
        if let Some(binding) = parse_envelope_binding(registry, loaded)? {
            bindings.push(binding);
        }
    }
    bindings.sort_by(|left, right| left.schema_id.cmp(&right.schema_id));
    Ok(bindings)
}

fn parse_envelope_binding(
    registry: &SchemaRegistry,
    loaded: &LoadedSchema,
) -> Result<Option<EnvelopeBinding>> {
    let document = &loaded.document;
    let properties = document
        .get("properties")
        .and_then(Value::as_object)
        .ok_or_else(|| SchemaToolError::msg(format!("{} missing properties", loaded.entry.id)))?;
    if !properties.contains_key("payload") {
        return Ok(None);
    }
    let branches = document.get("allOf").and_then(Value::as_array);
    let Some(branches) = branches else {
        return Ok(None);
    };
    if branches.is_empty() {
        return Ok(None);
    }

    let first_if_properties = branches[0]
        .pointer("/if/properties")
        .and_then(Value::as_object)
        .ok_or_else(|| mapping_error(&loaded.entry.id, "allOf branch missing if.properties"))?;
    let Some(discriminator) = first_if_properties.iter().find_map(|(name, schema)| {
        let is_string_const = schema.get("const").and_then(Value::as_str).is_some();
        let is_closed_enum = properties.get(name).is_some_and(is_string_enum);
        let all_branches_map_payload = branches.iter().all(|branch| {
            branch
                .pointer(&format!("/if/properties/{name}/const"))
                .and_then(Value::as_str)
                .is_some()
                && branch
                    .pointer("/then/properties/payload/$ref")
                    .and_then(Value::as_str)
                    .is_some()
        });
        (is_string_const && is_closed_enum && all_branches_map_payload).then(|| name.clone())
    }) else {
        return Ok(None);
    };
    let enum_values =
        string_enum_values(properties.get(&discriminator).ok_or_else(|| {
            mapping_error(&loaded.entry.id, "discriminator property is missing")
        })?)?;
    if enum_values.is_empty() {
        return Err(mapping_error(
            &loaded.entry.id,
            "discriminator enum is empty",
        ));
    }
    let enum_set: BTreeSet<_> = enum_values.iter().cloned().collect();
    if enum_set.len() != enum_values.len() {
        return Err(mapping_error(
            &loaded.entry.id,
            "discriminator enum contains duplicates",
        ));
    }

    let mut by_value = BTreeMap::new();
    let mut variant_to_value = BTreeMap::new();
    for (index, branch) in branches.iter().enumerate() {
        let branch_location = format!("{}/allOf/{index}", loaded.entry.id);
        let if_properties = branch
            .pointer("/if/properties")
            .and_then(Value::as_object)
            .ok_or_else(|| mapping_error(&branch_location, "missing if.properties"))?;
        let discriminator_schema = if_properties.get(&discriminator).ok_or_else(|| {
            mapping_error(
                &branch_location,
                "branch does not use the envelope discriminator",
            )
        })?;
        let value = discriminator_schema
            .get("const")
            .and_then(Value::as_str)
            .ok_or_else(|| mapping_error(&branch_location, "discriminator const must be a string"))?
            .to_string();
        let required = branch
            .pointer("/if/required")
            .and_then(Value::as_array)
            .is_some_and(|items| {
                items
                    .iter()
                    .any(|item| item.as_str() == Some(&discriminator))
            });
        if !required {
            return Err(mapping_error(
                &branch_location,
                "if.required must contain the discriminator",
            ));
        }
        let payload_ref = branch
            .pointer("/then/properties/payload/$ref")
            .and_then(Value::as_str)
            .ok_or_else(|| {
                mapping_error(&branch_location, "missing then.properties.payload.$ref")
            })?;
        let (payload_id, _) = resolve_ref(registry, &loaded.entry.id, payload_ref)?;
        if payload_ref.contains('#') {
            return Err(mapping_error(
                &branch_location,
                "typed payload mapping must reference a whole manifest schema",
            ));
        }
        let payload_loaded = registry.get(&payload_id)?;
        let payload_type = rust_type_name_for_schema(payload_loaded);
        let variant_name = to_pascal_case(&value);
        if by_value.contains_key(&value) {
            return Err(mapping_error(
                &branch_location,
                &format!("duplicate payload mapping for discriminator {value:?}"),
            ));
        }
        if let Some(previous) = variant_to_value.insert(variant_name.clone(), value.clone()) {
            return Err(mapping_error(
                &branch_location,
                &format!(
                    "Rust variant collision: discriminator values {previous:?} and {value:?} both map to {variant_name}"
                ),
            ));
        }
        let mapping = PayloadBinding {
            discriminator_value: value.clone(),
            variant_name,
            payload_type,
        };
        by_value.insert(value, mapping);
    }

    let mapping_set: BTreeSet<_> = by_value.keys().cloned().collect();
    if mapping_set != enum_set {
        let missing: Vec<_> = enum_set.difference(&mapping_set).cloned().collect();
        let extra: Vec<_> = mapping_set.difference(&enum_set).cloned().collect();
        return Err(mapping_error(
            &loaded.entry.id,
            &format!("discriminator enum/mapping mismatch; missing={missing:?}, extra={extra:?}"),
        ));
    }
    let mappings = enum_values
        .iter()
        .map(|value| {
            by_value
                .remove(value)
                .ok_or_else(|| mapping_error(&loaded.entry.id, "internal mapping order failure"))
        })
        .collect::<Result<Vec<_>>>()?;
    let base_name = typed_envelope_base_name(&loaded.entry.title);
    let api_prefix = if loaded.entry.title.starts_with("Kcp") {
        "Kcp"
    } else {
        ""
    };
    Ok(Some(EnvelopeBinding {
        schema_id: loaded.entry.id.clone(),
        title: loaded.entry.title.clone(),
        discriminator,
        payload_enum_name: format!("{api_prefix}{base_name}Payload"),
        typed_name: format!("Typed{api_prefix}{base_name}Envelope"),
        raw_name: format!("Raw{api_prefix}{base_name}Envelope"),
        mappings,
    }))
}

fn render_typed_envelope(
    registry: &SchemaRegistry,
    binding: &EnvelopeBinding,
    imports: &mut BTreeSet<String>,
) -> Result<String> {
    let loaded = registry.get(&binding.schema_id)?;
    let properties = loaded
        .document
        .get("properties")
        .and_then(Value::as_object)
        .ok_or_else(|| mapping_error(&binding.schema_id, "missing properties"))?;
    let required = required_set(&loaded.document);
    if !required.contains(&binding.discriminator) || !required.contains("payload") {
        return Err(mapping_error(
            &binding.schema_id,
            "typed envelope requires discriminator and payload fields",
        ));
    }

    let mut raw_fields = Vec::new();
    let mut public_fields = Vec::new();
    let mut assignments = Vec::new();
    let mut names: Vec<_> = properties.keys().cloned().collect();
    names.sort();
    for json_name in names {
        if json_name == binding.discriminator {
            raw_fields.push(render_wire_field(&json_name, "String", true));
            continue;
        }
        if json_name == "payload" {
            raw_fields.push(render_wire_field(&json_name, "Value", true));
            continue;
        }
        let schema = properties
            .get(&json_name)
            .ok_or_else(|| mapping_error(&binding.schema_id, "property disappeared"))?;
        let rust_type = typed_wire_type(registry, &binding.schema_id, schema, &json_name)?;
        collect_named_type_imports(&rust_type, imports);
        let field_type = if required.contains(&json_name) || rust_type.starts_with("Option<") {
            rust_type
        } else {
            format!("Option<{rust_type}>")
        };
        raw_fields.push(render_wire_field(&json_name, &field_type, true));
        public_fields.push(render_wire_field(&json_name, &field_type, false));
        assignments.push(format!(
            "            {}: raw.{},\n",
            to_snake_case(&json_name),
            to_snake_case(&json_name)
        ));
    }
    for mapping in &binding.mappings {
        imports.insert(mapping.payload_type.clone());
    }

    let mut out = String::new();
    out.push_str(&format!(
        "pub const {}_SCHEMA_ID: &str = {:?};\n\n",
        to_upper_snake_case(&binding.title),
        binding.schema_id
    ));
    out.push_str(&format!(
        "#[derive(Debug, Clone, PartialEq)]\npub struct {} {{\n",
        binding.typed_name
    ));
    for field in &public_fields {
        out.push_str(field);
    }
    out.push_str(&format!(
        "    pub {}: String,\n",
        to_snake_case(&binding.discriminator)
    ));
    out.push_str(&format!(
        "    pub payload: {},\n}}\n\n",
        binding.payload_enum_name
    ));

    out.push_str(&format!(
        "#[derive(Debug, Clone, PartialEq)]\npub enum {} {{\n",
        binding.payload_enum_name
    ));
    for mapping in &binding.mappings {
        out.push_str(&format!(
            "    {}(Box<{}>),\n",
            mapping.variant_name, mapping.payload_type
        ));
    }
    out.push_str("}\n\n");

    out.push_str(&format!(
        "#[derive(Debug, Deserialize)]\n#[serde(deny_unknown_fields)]\nstruct {} {{\n",
        binding.raw_name
    ));
    for field in &raw_fields {
        out.push_str(field);
    }
    out.push_str("}\n\n");

    let schema_const = format!("{}_SCHEMA_ID", to_upper_snake_case(&binding.title));
    let discriminator_field = to_snake_case(&binding.discriminator);
    out.push_str(&format!(
        "impl {} {{\n    pub fn decode(value: Value) -> Result<Self, ContractError> {{\n",
        binding.typed_name
    ));
    out.push_str(&format!(
        "        validate_json({schema_const}, &value)?;\n        Self::decode_after_validation(value)\n    }}\n\n    /// Decodes a value that has already passed this envelope's generated Schema.\n    ///\n    /// Callers must validate with the matching envelope Schema before using this method.\n    pub fn decode_after_validation(value: Value) -> Result<Self, ContractError> {{\n"
    ));
    out.push_str(&format!(
        "        let raw: {} = deserialize_wire({schema_const}, value)?;\n",
        binding.raw_name
    ));
    out.push_str(&format!(
        "        let discriminator = raw.{discriminator_field};\n"
    ));
    out.push_str("        let payload = match discriminator.as_str() {\n");
    for mapping in &binding.mappings {
        out.push_str(&format!(
            "            {:?} => {}::{}(Box::new(deserialize_payload({schema_const}, {:?}, raw.payload)?)),\n",
            mapping.discriminator_value,
            binding.payload_enum_name,
            mapping.variant_name,
            mapping.discriminator_value
        ));
    }
    out.push_str(&format!("            value => return Err(ContractError::GeneratedDiscriminatorMapping {{ schema_id: {schema_const}.to_string(), discriminator: value.to_string() }}),\n"));
    out.push_str("        };\n        Ok(Self {\n");
    for assignment in assignments {
        out.push_str(&assignment);
    }
    out.push_str(&format!("            {discriminator_field}: discriminator,\n            payload,\n        }})\n    }}\n}}\n"));
    Ok(out)
}

fn render_wire_field(json_name: &str, rust_type: &str, private: bool) -> String {
    let rust_name = to_snake_case(json_name);
    let mut out = String::new();
    if rust_name != json_name {
        out.push_str(&format!("    #[serde(rename = {:?})]\n", json_name));
    }
    let visibility = if private { "" } else { "pub " };
    out.push_str(&format!("    {visibility}{rust_name}: {rust_type},\n"));
    out
}

fn typed_wire_type(
    registry: &SchemaRegistry,
    base_id: &str,
    schema: &Value,
    field_name: &str,
) -> Result<String> {
    if schema.get("$ref").is_some() {
        ensure_ref_has_only_annotation_siblings(schema, base_id)?;
    }
    if let Some(reference) = schema.get("$ref").and_then(Value::as_str) {
        let (resolved_id, resolved) = resolve_ref(registry, base_id, reference)?;
        if reference.contains('#') {
            return typed_wire_type(registry, &resolved_id, &resolved, field_name);
        }
        return Ok(rust_type_name_for_schema(registry.get(&resolved_id)?));
    }
    if schema.get("const").is_some() {
        return Ok(format!(
            "{}{}",
            rust_type_name_for_schema(registry.get(base_id)?),
            to_pascal_case(field_name)
        ));
    }
    if is_string_enum(schema) || is_nullable_string_enum(schema) {
        return Ok(format!(
            "{}{}",
            rust_type_name_for_schema(registry.get(base_id)?),
            to_pascal_case(field_name)
        ));
    }
    match schema.get("type") {
        Some(Value::String(kind)) => typed_primitive_type(kind, schema),
        Some(Value::Array(kinds)) => {
            let non_null: Vec<_> = kinds
                .iter()
                .filter_map(Value::as_str)
                .filter(|kind| *kind != "null")
                .collect();
            if kinds.iter().any(|kind| kind.as_str() == Some("null")) && non_null.len() == 1 {
                Ok(format!(
                    "Option<{}>",
                    typed_primitive_type(non_null[0], schema)?
                ))
            } else {
                Err(mapping_error(
                    base_id,
                    "unsupported envelope field type union",
                ))
            }
        }
        _ => Err(mapping_error(base_id, "unsupported envelope field shape")),
    }
}

fn typed_primitive_type(kind: &str, schema: &Value) -> Result<String> {
    match kind {
        "null" => Ok("NullOnly".into()),
        "boolean" => Ok("bool".into()),
        "integer" => Ok("i64".into()),
        "number" => Ok("f64".into()),
        "string" => Ok("String".into()),
        "object" if schema.get("additionalProperties") == Some(&Value::Bool(true)) => {
            Ok("Value".into())
        }
        other => Err(mapping_error(
            "typed envelope field",
            &format!("unsupported primitive/container type {other}"),
        )),
    }
}

fn collect_named_type_imports(rust_type: &str, imports: &mut BTreeSet<String>) {
    for token in rust_type.split(|ch: char| !ch.is_ascii_alphanumeric() && ch != '_') {
        if token
            .chars()
            .next()
            .is_some_and(|first| first.is_ascii_uppercase())
            && !matches!(token, "Option" | "String" | "Value")
        {
            imports.insert(token.to_string());
        }
    }
}

fn typed_envelope_base_name(title: &str) -> String {
    let name = to_pascal_case(title);
    let without_prefix = name.strip_prefix("Kcp").unwrap_or(&name);
    without_prefix
        .strip_suffix("Envelope")
        .unwrap_or(without_prefix)
        .to_string()
}

fn to_upper_snake_case(input: &str) -> String {
    to_snake_case(input).to_ascii_uppercase()
}

fn mapping_error(location: &str, detail: &str) -> anyhow::Error {
    SchemaToolError::msg(format!(
        "conditional payload mapping error in {location}: {detail}"
    ))
    .into()
}

fn render_typed_decode_helpers() -> &'static str {
    "fn deserialize_wire<T>(schema_id: &str, value: Value) -> Result<T, ContractError>\nwhere\n    T: for<'de> Deserialize<'de>,\n{\n    serde_json::from_value(value).map_err(|error| ContractError::WireDecodeAfterSchema {\n        schema_id: schema_id.to_string(),\n        detail: error.to_string(),\n    })\n}\n\nfn deserialize_payload<T>(\n    schema_id: &str,\n    discriminator: &str,\n    value: Value,\n) -> Result<T, ContractError>\nwhere\n    T: for<'de> Deserialize<'de>,\n{\n    serde_json::from_value(value).map_err(|error| ContractError::PayloadDecodeAfterSchema {\n        schema_id: schema_id.to_string(),\n        discriminator: discriminator.to_string(),\n        detail: error.to_string(),\n    })\n}\n"
}

fn envelope_discriminators(
    registry: &SchemaRegistry,
    id_suffix: &str,
    property: &str,
) -> Result<Vec<String>> {
    let loaded = registry
        .by_id
        .values()
        .find(|loaded| loaded.entry.id.ends_with(id_suffix))
        .ok_or_else(|| SchemaToolError::msg(format!("manifest missing {id_suffix}")))?;
    string_enum_values(
        loaded
            .document
            .pointer(&format!("/properties/{property}"))
            .ok_or_else(|| {
                SchemaToolError::msg(format!("{} missing {property}", loaded.entry.id))
            })?,
    )
}

fn audit_schema_tree(schema: &Value, location: &str) -> Result<()> {
    let Some(object) = schema.as_object() else {
        if schema.is_boolean() {
            return Ok(());
        }
        return Err(unsupported(
            "schema",
            location,
            "schema node must be an object or boolean",
        ));
    };
    validate_supported_schema_node(schema, location)?;

    for container in ["properties", "$defs"] {
        if let Some(children) = object.get(container).and_then(Value::as_object) {
            for (name, child) in children {
                audit_schema_tree(child, &format!("{location}/{container}/{name}"))?;
            }
        }
    }
    for keyword in ["items", "additionalProperties", "if", "then", "else"] {
        if let Some(child) = object.get(keyword) {
            if keyword != "additionalProperties" || !child.is_boolean() {
                audit_schema_tree(child, &format!("{location}/{keyword}"))?;
            }
        }
    }
    for keyword in ["oneOf", "allOf"] {
        if let Some(children) = object.get(keyword).and_then(Value::as_array) {
            for (index, child) in children.iter().enumerate() {
                audit_schema_tree(child, &format!("{location}/{keyword}/{index}"))?;
            }
        }
    }
    Ok(())
}

fn validate_supported_schema_node(schema: &Value, location: &str) -> Result<()> {
    let Some(object) = schema.as_object() else {
        return Err(unsupported(
            "schema",
            location,
            "boolean schemas are not supported by codegen",
        ));
    };
    const KNOWN_KEYWORDS: &[&str] = &[
        "$schema",
        "$id",
        "$ref",
        "$defs",
        "title",
        "description",
        "type",
        "properties",
        "required",
        "additionalProperties",
        "items",
        "enum",
        "const",
        "oneOf",
        "allOf",
        "if",
        "then",
        "else",
        "format",
        "minimum",
        "maximum",
        "minLength",
        "pattern",
        "minItems",
        "uniqueItems",
    ];
    for keyword in object.keys() {
        if !KNOWN_KEYWORDS.contains(&keyword.as_str()) {
            return Err(unsupported(
                keyword,
                location,
                "unknown schema keyword is not classified by the restricted codegen",
            ));
        }
    }
    const SHAPE_UNSUPPORTED: &[&str] = &[
        "anyOf",
        "not",
        "patternProperties",
        "dependentSchemas",
        "dependentRequired",
        "prefixItems",
        "contains",
        "propertyNames",
        "unevaluatedProperties",
        "unevaluatedItems",
        "contentSchema",
    ];
    for keyword in SHAPE_UNSUPPORTED {
        if object.contains_key(*keyword) {
            return Err(unsupported(
                keyword,
                location,
                "shape keyword is not supported by restricted codegen",
            ));
        }
    }
    if let Some(additional) = object.get("additionalProperties") {
        if !additional.is_boolean() {
            return Err(unsupported(
                "additionalProperties",
                location,
                "schema-valued additionalProperties is not supported",
            ));
        }
    }
    Ok(())
}

fn ensure_const_matches_type(schema: &Value, value: &Value, location: &str) -> Result<()> {
    let valid = match schema.get("type").and_then(Value::as_str) {
        Some("string") => value.is_string(),
        Some("integer") => value.as_i64().is_some() || value.as_u64().is_some(),
        Some("boolean") => value.is_boolean(),
        Some("null") => value.is_null(),
        Some(_) | None => true,
    };
    if valid {
        Ok(())
    } else {
        Err(unsupported(
            "const",
            location,
            "const value does not match declared type",
        ))
    }
}

fn unsupported(keyword: &str, location: &str, detail: &str) -> anyhow::Error {
    SchemaToolError::UnsupportedKeyword {
        keyword: keyword.into(),
        location: location.into(),
        detail: detail.into(),
    }
    .into()
}

fn is_string_enum(schema: &Value) -> bool {
    schema
        .get("enum")
        .and_then(Value::as_array)
        .is_some_and(|values| !values.is_empty() && values.iter().all(Value::is_string))
}

fn is_nullable_string_enum(schema: &Value) -> bool {
    schema
        .get("enum")
        .and_then(Value::as_array)
        .is_some_and(|values| {
            values.iter().any(Value::is_null)
                && values
                    .iter()
                    .all(|value| value.is_null() || value.is_string())
        })
}

fn string_enum_values(schema: &Value) -> Result<Vec<String>> {
    schema
        .get("enum")
        .and_then(Value::as_array)
        .ok_or_else(|| SchemaToolError::msg("enum schema missing enum array"))?
        .iter()
        .filter(|value| !value.is_null())
        .map(|value| {
            value
                .as_str()
                .map(str::to_owned)
                .ok_or_else(|| anyhow::Error::from(SchemaToolError::msg("non-string enum value")))
        })
        .collect()
}

fn is_object_schema(schema: &Value) -> bool {
    schema.get("type").and_then(Value::as_str) == Some("object")
        || schema.get("properties").is_some()
}

fn is_null_type(schema: &Value) -> bool {
    schema.get("type").and_then(Value::as_str) == Some("null")
}

fn ensure_ref_has_only_annotation_siblings(schema: &Value, location: &str) -> Result<()> {
    let object = schema.as_object().ok_or_else(|| {
        unsupported(
            "$ref",
            location,
            "$ref node must be an object in restricted codegen",
        )
    })?;
    const ALLOWED_REF_KEYS: &[&str] = &["$ref", "title", "description"];
    if let Some(keyword) = object
        .keys()
        .find(|keyword| !ALLOWED_REF_KEYS.contains(&keyword.as_str()))
    {
        return Err(unsupported(
            keyword,
            location,
            "$ref siblings with validation or shape semantics are not supported; compose them in an explicit source Schema instead",
        ));
    }
    Ok(())
}

/// Derive whether a property Schema accepts JSON `null` under the restricted codegen surface.
///
/// Fail closed when the shape is outside the supported nullability forms: generation must not
/// guess between omission and explicit null.
fn schema_allows_null(registry: &SchemaRegistry, base_id: &str, schema: &Value) -> Result<bool> {
    if schema == &Value::Bool(true) {
        // `true` accepts every JSON value, including null.
        return Ok(true);
    }
    if schema == &Value::Bool(false) {
        return Ok(false);
    }

    if let Some(reference) = schema.get("$ref").and_then(Value::as_str) {
        ensure_ref_has_only_annotation_siblings(schema, base_id)?;
        let (resolved_id, resolved_schema) = resolve_ref(registry, base_id, reference)?;
        return schema_allows_null(registry, &resolved_id, &resolved_schema);
    }

    if let Some(variants) = schema.get("oneOf").and_then(Value::as_array) {
        // Restricted codegen only accepts nullable oneOf with exactly [null, T].
        // Mirror that surface: nullability is true iff one branch is the null type.
        // Ambiguous or unsupported oneOf is rejected by schema_to_type separately.
        return Ok(variants.iter().any(is_null_type));
    }

    if is_nullable_string_enum(schema) {
        return Ok(true);
    }
    if is_string_enum(schema) {
        return Ok(false);
    }

    if let Some(value) = schema.get("const") {
        return Ok(value.is_null());
    }

    match schema.get("type") {
        Some(Value::String(kind)) => Ok(kind == "null"),
        Some(Value::Array(kinds)) => {
            if kinds.iter().any(|value| !value.is_string()) {
                return Err(unsupported(
                    "type",
                    base_id,
                    "type union contains a non-string member; cannot derive nullability",
                ));
            }
            Ok(kinds.iter().any(|value| value.as_str() == Some("null")))
        }
        None if schema.get("properties").is_some() => Ok(false),
        None => Err(unsupported(
            "type",
            base_id,
            "cannot derive nullability without type/$ref/enum/const/oneOf",
        )),
        Some(other) => Err(unsupported(
            "type",
            base_id,
            &format!("unsupported type form for nullability: {other}"),
        )),
    }
}

fn required_set(schema: &Value) -> BTreeSet<String> {
    schema
        .get("required")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .filter_map(Value::as_str)
        .map(str::to_owned)
        .collect()
}

fn rust_type_name_for_schema(loaded: &LoadedSchema) -> String {
    if loaded.entry.title.is_empty() {
        rust_type_name_from_id(&loaded.entry.id)
    } else {
        to_pascal_case(&loaded.entry.title)
    }
}

fn rust_type_name_from_id(id: &str) -> String {
    to_pascal_case(
        id.rsplit('/')
            .next()
            .unwrap_or(id)
            .trim_end_matches(".json"),
    )
}

fn to_pascal_case(input: &str) -> String {
    let mut out = String::new();
    let mut capitalize = true;
    for ch in input.chars() {
        if ch.is_ascii_alphanumeric() {
            if capitalize {
                out.extend(ch.to_uppercase());
                capitalize = false;
            } else {
                out.push(ch);
            }
        } else {
            capitalize = true;
        }
    }
    if out.is_empty() {
        "Anonymous".into()
    } else if out.starts_with(|ch: char| ch.is_ascii_digit()) {
        format!("N{out}")
    } else {
        out
    }
}

fn to_snake_case(input: &str) -> String {
    let mut out = String::new();
    let mut previous_underscore = true;
    for ch in input.chars() {
        if ch.is_ascii_uppercase() {
            if !previous_underscore && !out.is_empty() {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
            previous_underscore = false;
        } else if ch.is_ascii_alphanumeric() {
            out.push(ch.to_ascii_lowercase());
            previous_underscore = false;
        } else if !previous_underscore {
            out.push('_');
            previous_underscore = true;
        }
    }
    let value = out.trim_matches('_');
    if matches!(
        value,
        "type" | "ref" | "self" | "super" | "crate" | "match" | "move" | "where" | "as"
    ) {
        format!("{value}_")
    } else if value.is_empty() {
        "value".into()
    } else {
        value.into()
    }
}

fn to_enum_variant(value: &str) -> String {
    if value.len() == 2 && value.starts_with('S') && value.as_bytes()[1].is_ascii_digit() {
        value.into()
    } else {
        to_pascal_case(value)
    }
}
