use crate::codegen;
use crate::manifest::SchemaRegistry;
use crate::paths;
use crate::resolve;
use anyhow::{Context, Result};
use std::path::Path;

pub fn run(repo_root: &Path) -> Result<()> {
    let registry = SchemaRegistry::load(repo_root)?;
    resolve::check_all_refs(&registry)?;

    let module = codegen::generate_rust_module(&registry)?;
    let catalog = codegen::generate_catalog_module(&registry)?;
    let typed = codegen::generate_typed_module(&registry)?;
    let generated_dir = paths::generated_dir(repo_root);
    std::fs::create_dir_all(&generated_dir)
        .with_context(|| format!("create {}", generated_dir.display()))?;

    let types_path = generated_dir.join("types.rs");
    let catalog_path = generated_dir.join("catalog.rs");
    let typed_path = generated_dir.join("typed.rs");
    write_if_changed(&types_path, &module)?;
    write_if_changed(&catalog_path, &catalog)?;
    write_if_changed(&typed_path, &typed)?;

    let mod_rs = "\
// @generated by schema-tool. DO NOT EDIT BY HAND.
// GENERATED module root for kernel-contracts.

//! Auto-generated contract types from `schemas/source`.

mod catalog;
mod typed;
mod types;

pub use catalog::*;
pub use typed::*;
pub use types::*;
";
    let mod_path = generated_dir.join("mod.rs");
    write_if_changed(&mod_path, mod_rs)?;

    println!(
        "generated {} schemas into {}",
        registry.manifest.schemas.len(),
        generated_dir.display()
    );
    Ok(())
}

fn write_if_changed(path: &Path, content: &str) -> Result<()> {
    let normalized = ensure_trailing_newline(content);
    if path.is_file() {
        let existing = std::fs::read_to_string(path)
            .with_context(|| format!("read existing {}", path.display()))?;
        if existing == normalized {
            return Ok(());
        }
    }
    std::fs::write(path, normalized.as_bytes())
        .with_context(|| format!("write {}", path.display()))?;
    Ok(())
}

fn ensure_trailing_newline(content: &str) -> String {
    format!("{}\n", content.trim_end_matches(['\r', '\n']))
}
