//! Rust renderer that consumes a language-neutral [`TargetContractGraph`].
//!
//! All Rust naming, keywords, type mapping, serde attributes, variant names,
//! `include_str!` paths, and output paths are decided here. This module must
//! not re-read Schema shape keywords or `serde_json::Value` Schema documents.
//!
//! ## Identity separation
//!
//! - [`ContractTypeId`] is the canonical graph node (`$id` + JSON Pointer).
//! - [`RustDeclarationId`] is a projected declaration that may clone a single
//!   graph node under a use-site lineage (HEAD preserves
//!   `PolicyRuleCreatedBy` / `PolicyRuleUpdatedBy` as distinct declarations for
//!   one `/$defs/actorEntryPoint` node).
//!
//! Whole-schema `$ref` roots are shared (`SharedRoot`). Fragment / inline named
//! shapes used from a property path are projected as
//! `NominalInstantiation { canonical, use_site_lineage }`. The Rust symbol name
//! is stored independently on the projected declaration.
//!
//! ## Recursive layout
//!
//! After projection, a direct-value dependency graph is built (Named direct;
//! Nullable / field Optional direct; Array indirect). Deterministic SCCs wrap
//! same-component direct `Named` edges in [`RustTypeExpr::Boxed`]. Arrays do
//! not need `Box`.

use crate::contract_model::{
    ConstJson, ContractTypeId, EnvelopeWireBinding, Nullability, Presence, ScalarKind,
    SourceUseSite, TargetContractGraph, TypeExpr, TypeShape, TypeUse, UnknownFieldPolicy,
};
use crate::error::SchemaToolError;
use crate::names::{to_pascal_case, to_snake_case, to_upper_snake_case};
use anyhow::Result;
use std::collections::{BTreeMap, BTreeSet};
use std::fmt;

const GENERATED_HEADER: &str = "\
// @generated by schema-tool. DO NOT EDIT BY HAND.
// GENERATED from schemas/source via deterministic restricted codegen.
// Source of truth: JSON Schema Draft 2020-12 under schemas/source/.
";

pub const GENERATED_MOD_RS: &str = "\
// @generated by schema-tool. DO NOT EDIT BY HAND.
// GENERATED module root for kernel-contracts.

//! Auto-generated contract types from `schemas/source`.

mod catalog;
mod typed;
mod types;

pub use catalog::*;
pub use typed::*;
pub use types::*;
";

/// Relative directory for Rust generated artifacts under the repository root.
pub const RUST_GENERATED_DIR: &str = "rust/crates/kernel-contracts/src/generated";

// ---------------------------------------------------------------------------
// Projection identity
// ---------------------------------------------------------------------------

/// Rust declaration identity. Distinct from [`ContractTypeId`].
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum RustDeclarationId {
    /// One shared declaration for a whole-schema root ref.
    SharedRoot { schema_id: String },
    /// Named projection of a graph node under a use-site lineage.
    ///
    /// `use_site_lineage` is the chain of schema use-sites from the owning root
    /// projection down to this declaration. The Rust symbol name is **not** part
    /// of the identity; it lives on [`ProjectedDecl::rust_name`].
    NominalInstantiation {
        canonical: ContractTypeId,
        use_site_lineage: Vec<SourceUseSite>,
    },
}

impl RustDeclarationId {
    fn display(&self) -> String {
        match self {
            Self::SharedRoot { schema_id } => format!("shared:{schema_id}"),
            Self::NominalInstantiation {
                canonical,
                use_site_lineage,
            } => {
                let sites: Vec<String> = use_site_lineage
                    .iter()
                    .map(SourceUseSite::display)
                    .collect();
                format!("nominal:{}@{}", sites.join(" > "), canonical.display())
            }
        }
    }
}

impl fmt::Display for RustDeclarationId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.display())
    }
}

/// Projected Rust type expression (renderer-local; never stored in the graph).
#[derive(Debug, Clone, PartialEq, Eq)]
enum RustTypeExpr {
    Scalar(ScalarKind),
    AnyJson,
    Array(Box<RustTypeExpr>),
    Nullable(Box<RustTypeExpr>),
    Named(RustDeclarationId),
    /// Direct recursive ownership within an SCC (inserted by layout pass).
    Boxed(Box<RustTypeExpr>),
}

/// One projected declaration body.
#[derive(Debug, Clone)]
enum ProjectedShape {
    Object {
        fields: Vec<ProjectedField>,
        unknown_field_policy: UnknownFieldPolicy,
    },
    TaggedUnion {
        discriminator: String,
        variants: Vec<ProjectedVariant>,
    },
    StringEnum {
        values: Vec<String>,
    },
    Const {
        value: ConstJson,
    },
}

#[derive(Debug, Clone)]
struct ProjectedField {
    json_name: String,
    ty: RustTypeExpr,
    presence: Presence,
    nullability: Nullability,
}

#[derive(Debug, Clone)]
struct ProjectedVariant {
    tag: String,
    object_type_id: ContractTypeId,
    source: SourceUseSite,
    rust_name: String,
    fields: Vec<ProjectedField>,
}

#[derive(Debug, Clone)]
struct ProjectedDecl {
    id: RustDeclarationId,
    /// Source schema `$id` for doc comments (HEAD uses the owning schema id).
    doc_schema_id: String,
    rust_name: String,
    shape: ProjectedShape,
}

/// Single computed Rust projection for a [`TargetContractGraph`].
///
/// `render_types_module_from_projection` and `render_typed_module_from_projection`
/// must consume the **same** instance so declaration names and SCC layout stay
/// bijective across artifacts. Catalog does not need projection and may render
/// directly from the graph.
#[derive(Debug, Clone)]
pub struct RustProjection {
    decls: Vec<ProjectedDecl>,
    names: BTreeMap<RustDeclarationId, String>,
    /// SharedRoot schema_id -> rust name (payload / envelope root lookup).
    root_names: BTreeMap<String, String>,
}

impl RustProjection {
    /// Declarations in stable emission order (by rust_name).
    pub fn declarations(&self) -> impl Iterator<Item = (&RustDeclarationId, &str)> + '_ {
        self.decls.iter().map(|d| (&d.id, d.rust_name.as_str()))
    }

    /// Rust symbol for a declaration identity, if present.
    pub fn name_of(&self, id: &RustDeclarationId) -> Option<&str> {
        self.names.get(id).map(String::as_str)
    }

    /// Rust symbol for a whole-schema SharedRoot, if projected.
    pub fn root_name(&self, schema_id: &str) -> Option<&str> {
        self.root_names.get(schema_id).map(String::as_str)
    }

    /// All projected declaration identities for a canonical graph node.
    pub fn decls_for_canonical(&self, canonical: &ContractTypeId) -> Vec<&RustDeclarationId> {
        self.decls
            .iter()
            .filter_map(|decl| match &decl.id {
                RustDeclarationId::SharedRoot { schema_id }
                    if schema_id == &canonical.schema_id && canonical.is_root() =>
                {
                    Some(&decl.id)
                }
                RustDeclarationId::NominalInstantiation {
                    canonical: node, ..
                } if node == canonical => Some(&decl.id),
                _ => None,
            })
            .collect()
    }

    /// Count of NominalInstantiation declarations for `canonical`.
    pub fn nominal_count_for(&self, canonical: &ContractTypeId) -> usize {
        self.decls
            .iter()
            .filter(|decl| {
                matches!(
                    &decl.id,
                    RustDeclarationId::NominalInstantiation {
                        canonical: node,
                        ..
                    } if node == canonical
                )
            })
            .count()
    }

    /// Field type expression rendered for TypesModule context (inspection helper).
    pub fn field_type_expr(&self, decl_rust_name: &str, json_field: &str) -> Result<String> {
        let decl = self
            .decls
            .iter()
            .find(|d| d.rust_name == decl_rust_name)
            .ok_or_else(|| {
                SchemaToolError::msg(format!(
                    "projection has no declaration named {decl_rust_name}"
                ))
            })?;
        let ProjectedShape::Object { fields, .. } = &decl.shape else {
            return Err(SchemaToolError::msg(format!(
                "declaration {decl_rust_name} is not an object"
            ))
            .into());
        };
        let field = fields
            .iter()
            .find(|f| f.json_name == json_field)
            .ok_or_else(|| {
                SchemaToolError::msg(format!(
                    "declaration {decl_rust_name} has no field {json_field}"
                ))
            })?;
        let mut rendered =
            render_rust_type_expr(&field.ty, &self.names, TypeRenderContext::TypesModule)?;
        if field.presence == Presence::Optional && !rendered.starts_with("Option<") {
            rendered = format!("Option<{rendered}>");
        }
        Ok(rendered)
    }
}

/// Project the graph exactly once into a reusable [`RustProjection`].
pub fn project_rust(graph: &TargetContractGraph) -> Result<RustProjection> {
    let decls = Projector::new(graph).project_all()?;
    let names: BTreeMap<RustDeclarationId, String> = decls
        .iter()
        .map(|d| (d.id.clone(), d.rust_name.clone()))
        .collect();
    let root_names: BTreeMap<String, String> = decls
        .iter()
        .filter_map(|d| match &d.id {
            RustDeclarationId::SharedRoot { schema_id } => {
                Some((schema_id.clone(), d.rust_name.clone()))
            }
            _ => None,
        })
        .collect();
    Ok(RustProjection {
        decls,
        names,
        root_names,
    })
}

// ---------------------------------------------------------------------------
// Projection engine
// ---------------------------------------------------------------------------

struct Projector<'a> {
    graph: &'a TargetContractGraph,
    decls: BTreeMap<RustDeclarationId, ProjectedDecl>,
    /// Declarations currently being projected (cycle termination by decl id).
    projecting: BTreeSet<RustDeclarationId>,
    /// Canonical currently on the projection stack -> active decl (backedge reuse).
    /// Prevents infinite nominal lineage growth on recursive shapes.
    active_by_canonical: BTreeMap<ContractTypeId, RustDeclarationId>,
}

impl<'a> Projector<'a> {
    fn new(graph: &'a TargetContractGraph) -> Self {
        Self {
            graph,
            decls: BTreeMap::new(),
            projecting: BTreeSet::new(),
            active_by_canonical: BTreeMap::new(),
        }
    }

    fn project_all(mut self) -> Result<Vec<ProjectedDecl>> {
        // Project every root schema as a shared root declaration.
        for schema_id in &self.graph.source_schema_ids {
            let root = ContractTypeId::root(schema_id);
            if self.graph.nodes.contains_key(&root) {
                self.ensure_shared_root(&root)?;
            }
        }
        // Recursive layout: Box direct edges inside SCCs.
        apply_recursive_layout(&mut self.decls)?;

        // Stable order by rust_name for emission (matches HEAD BTreeMap-by-name).
        let mut out: Vec<_> = self.decls.into_values().collect();
        out.sort_by(|a, b| a.rust_name.cmp(&b.rust_name));
        // Fail closed on symbol collisions.
        let mut used: BTreeMap<String, RustDeclarationId> = BTreeMap::new();
        for decl in &out {
            if let Some(previous) = used.get(&decl.rust_name) {
                if previous != &decl.id {
                    return Err(SchemaToolError::msg(format!(
                        "Rust type name collision: `{}` is required by both {} and {} (canonical/use-site identities)",
                        decl.rust_name,
                        previous.display(),
                        decl.id.display()
                    ))
                    .into());
                }
            }
            used.insert(decl.rust_name.clone(), decl.id.clone());
            audit_decl_internal_collisions(decl)?;
        }
        Ok(out)
    }

    fn ensure_shared_root(&mut self, root: &ContractTypeId) -> Result<RustDeclarationId> {
        let id = RustDeclarationId::SharedRoot {
            schema_id: root.schema_id.clone(),
        };
        if self.decls.contains_key(&id) || !self.projecting.insert(id.clone()) {
            return Ok(id);
        }
        self.active_by_canonical.insert(root.clone(), id.clone());
        let node = self.graph.nodes.get(root).ok_or_else(|| {
            SchemaToolError::msg(format!(
                "internal renderer error: missing graph node {}",
                root.display()
            ))
        })?;
        let rust_name = root_rust_name(node);
        let shape = self.project_shape(&node.shape, root, &rust_name, &[], &root.schema_id)?;
        self.projecting.remove(&id);
        self.active_by_canonical.remove(root);
        self.decls.insert(
            id.clone(),
            ProjectedDecl {
                id: id.clone(),
                doc_schema_id: root.schema_id.clone(),
                rust_name,
                shape,
            },
        );
        Ok(id)
    }

    fn ensure_nominal(
        &mut self,
        canonical: &ContractTypeId,
        rust_name: &str,
        use_site_lineage: &[SourceUseSite],
        doc_schema_id: &str,
    ) -> Result<RustDeclarationId> {
        // Backedge reuse: if this canonical is already on the projection stack,
        // return the active declaration instead of growing lineage forever.
        if let Some(active) = self.active_by_canonical.get(canonical) {
            return Ok(active.clone());
        }

        let id = RustDeclarationId::NominalInstantiation {
            canonical: canonical.clone(),
            use_site_lineage: use_site_lineage.to_vec(),
        };
        if self.decls.contains_key(&id) || !self.projecting.insert(id.clone()) {
            return Ok(id);
        }
        self.active_by_canonical
            .insert(canonical.clone(), id.clone());
        let node = self.graph.nodes.get(canonical).ok_or_else(|| {
            SchemaToolError::msg(format!(
                "internal renderer error: missing graph node {} for name {rust_name} (use-sites: {})",
                canonical.display(),
                use_site_lineage
                    .iter()
                    .map(SourceUseSite::display)
                    .collect::<Vec<_>>()
                    .join(" > ")
            ))
        })?;
        let shape = self.project_shape(
            &node.shape,
            canonical,
            rust_name,
            use_site_lineage,
            doc_schema_id,
        )?;
        self.projecting.remove(&id);
        self.active_by_canonical.remove(canonical);
        self.decls.insert(
            id.clone(),
            ProjectedDecl {
                id: id.clone(),
                doc_schema_id: doc_schema_id.to_string(),
                rust_name: rust_name.to_string(),
                shape,
            },
        );
        Ok(id)
    }

    fn project_shape(
        &mut self,
        shape: &TypeShape,
        canonical: &ContractTypeId,
        rust_name: &str,
        use_site_lineage: &[SourceUseSite],
        doc_schema_id: &str,
    ) -> Result<ProjectedShape> {
        match shape {
            TypeShape::Object {
                fields,
                unknown_field_policy,
            } => {
                let mut projected = Vec::new();
                for field in fields {
                    let field_name = format!("{rust_name}{}", to_pascal_case(&field.json_name));
                    let child_lineage = {
                        let mut lineage = use_site_lineage.to_vec();
                        lineage.push(field.ty.source.clone());
                        lineage
                    };
                    let ty = self.project_type_use(
                        &field.ty,
                        &field_name,
                        &child_lineage,
                        doc_schema_id,
                    )?;
                    projected.push(ProjectedField {
                        json_name: field.json_name.clone(),
                        ty,
                        presence: field.presence,
                        nullability: field.nullability,
                    });
                }
                Ok(ProjectedShape::Object {
                    fields: projected,
                    unknown_field_policy: *unknown_field_policy,
                })
            }
            TypeShape::TaggedUnion {
                discriminator,
                branches,
                unknown_field_policy,
            } => {
                if *unknown_field_policy != UnknownFieldPolicy::Forbid {
                    return Err(SchemaToolError::msg(format!(
                        "unsupported tagged-union unknown-field policy at {}",
                        canonical.display()
                    ))
                    .into());
                }
                let mut variants = Vec::new();
                for branch in branches {
                    let branch_node =
                        self.graph
                            .nodes
                            .get(&branch.object_type_id)
                            .ok_or_else(|| {
                                SchemaToolError::msg(format!(
                                    "missing tagged-union branch {} at {} (arm {})",
                                    branch.tag,
                                    branch.object_type_id.display(),
                                    branch.source.display()
                                ))
                            })?;
                    let TypeShape::Object { fields, .. } = &branch_node.shape else {
                        return Err(SchemaToolError::msg(format!(
                            "tagged-union branch {} at {} (arm {}) is not an object",
                            branch.tag,
                            branch.object_type_id.display(),
                            branch.source.display()
                        ))
                        .into());
                    };
                    let variant_name = rust_enum_variant(&branch.tag);
                    let mut projected = Vec::new();
                    for field in fields
                        .iter()
                        .filter(|field| field.json_name != *discriminator)
                    {
                        let field_name = format!(
                            "{rust_name}{variant_name}{}",
                            to_pascal_case(&field.json_name)
                        );
                        let mut lineage = use_site_lineage.to_vec();
                        lineage.push(field.ty.source.clone());
                        projected.push(ProjectedField {
                            json_name: field.json_name.clone(),
                            ty: self.project_type_use(
                                &field.ty,
                                &field_name,
                                &lineage,
                                doc_schema_id,
                            )?,
                            presence: field.presence,
                            nullability: field.nullability,
                        });
                    }
                    variants.push(ProjectedVariant {
                        tag: branch.tag.clone(),
                        object_type_id: branch.object_type_id.clone(),
                        source: branch.source.clone(),
                        rust_name: variant_name,
                        fields: projected,
                    });
                }
                Ok(ProjectedShape::TaggedUnion {
                    discriminator: discriminator.clone(),
                    variants,
                })
            }
            TypeShape::StringEnum { values } => Ok(ProjectedShape::StringEnum {
                values: values.clone(),
            }),
            TypeShape::Const { value } => Ok(ProjectedShape::Const {
                value: value.clone(),
            }),
            // Named declarations are only emitted for Object / StringEnum / Const
            // (matching HEAD). Scalar/Any/Array/Nullable shapes are inlined at use sites
            // and must not become standalone declarations.
            TypeShape::Scalar { .. }
            | TypeShape::AnyJson
            | TypeShape::Array { .. }
            | TypeShape::Nullable { .. } => Err(SchemaToolError::msg(format!(
                "internal renderer error: cannot project non-named shape at {} (name {rust_name})",
                canonical.display()
            ))
            .into()),
        }
    }

    fn project_type_use(
        &mut self,
        ty: &TypeUse,
        rust_name: &str,
        use_site_lineage: &[SourceUseSite],
        doc_schema_id: &str,
    ) -> Result<RustTypeExpr> {
        match &ty.expr {
            TypeExpr::Scalar { scalar } => Ok(RustTypeExpr::Scalar(*scalar)),
            TypeExpr::AnyJson => Ok(RustTypeExpr::AnyJson),
            TypeExpr::Array { items } => {
                let item_name = format!("{rust_name}Item");
                let mut item_lineage = use_site_lineage.to_vec();
                // Array items keep the array use-site; item schema source is on items.source.
                item_lineage.push(items.source.clone());
                Ok(RustTypeExpr::Array(Box::new(self.project_type_use(
                    items,
                    &item_name,
                    &item_lineage,
                    doc_schema_id,
                )?)))
            }
            TypeExpr::Nullable { inner } => Ok(RustTypeExpr::Nullable(Box::new(
                self.project_type_use(inner, rust_name, use_site_lineage, doc_schema_id)?,
            ))),
            TypeExpr::Reference { id } => {
                self.project_reference(id, rust_name, use_site_lineage, doc_schema_id)
            }
        }
    }

    fn project_reference(
        &mut self,
        id: &ContractTypeId,
        rust_name: &str,
        use_site_lineage: &[SourceUseSite],
        doc_schema_id: &str,
    ) -> Result<RustTypeExpr> {
        let node = self.graph.nodes.get(id).ok_or_else(|| {
            SchemaToolError::msg(format!(
                "internal renderer error: missing referenced node {} (name {rust_name}, use-sites {})",
                id.display(),
                use_site_lineage
                    .iter()
                    .map(SourceUseSite::display)
                    .collect::<Vec<_>>()
                    .join(" > ")
            ))
        })?;

        // Whole-schema roots are always shared (one declaration per schema_id).
        if id.is_root() {
            let decl = self.ensure_shared_root(id)?;
            return Ok(RustTypeExpr::Named(decl));
        }

        // Named shapes under a fragment / inline pointer: clone per use-site lineage
        // so shared $defs become PolicyRuleCreatedBy / PolicyRuleUpdatedBy.
        if shape_is_named(&node.shape) {
            let decl = self.ensure_nominal(id, rust_name, use_site_lineage, doc_schema_id)?;
            return Ok(RustTypeExpr::Named(decl));
        }

        // Non-named shapes referenced by identity: project inline.
        match &node.shape {
            TypeShape::Scalar { scalar } => Ok(RustTypeExpr::Scalar(*scalar)),
            TypeShape::AnyJson => Ok(RustTypeExpr::AnyJson),
            TypeShape::Array { items } => {
                let item_name = format!("{rust_name}Item");
                let mut item_lineage = use_site_lineage.to_vec();
                item_lineage.push(items.source.clone());
                Ok(RustTypeExpr::Array(Box::new(self.project_type_use(
                    items,
                    &item_name,
                    &item_lineage,
                    doc_schema_id,
                )?)))
            }
            TypeShape::Nullable { inner } => Ok(RustTypeExpr::Nullable(Box::new(
                self.project_type_use(inner, rust_name, use_site_lineage, doc_schema_id)?,
            ))),
            TypeShape::Object { .. }
            | TypeShape::TaggedUnion { .. }
            | TypeShape::StringEnum { .. }
            | TypeShape::Const { .. } => Err(SchemaToolError::msg(format!(
                "internal renderer error: named shape for {} fell through without declaration",
                id.display()
            ))
            .into()),
        }
    }
}

// ---------------------------------------------------------------------------
// Recursive layout (direct-value SCC + Box)
// ---------------------------------------------------------------------------

fn apply_recursive_layout(decls: &mut BTreeMap<RustDeclarationId, ProjectedDecl>) -> Result<()> {
    // Direct-value dependency edges: Named is direct; Nullable unwraps as direct;
    // Array is indirect (no edge). Field presence Optional is still direct ownership.
    let mut edges: BTreeMap<RustDeclarationId, BTreeSet<RustDeclarationId>> = BTreeMap::new();
    for id in decls.keys() {
        edges.entry(id.clone()).or_default();
    }
    for (id, decl) in decls.iter() {
        match &decl.shape {
            ProjectedShape::Object { fields, .. } => {
                for field in fields {
                    for dep in direct_named_deps(&field.ty) {
                        edges.entry(id.clone()).or_default().insert(dep);
                    }
                }
            }
            ProjectedShape::TaggedUnion { variants, .. } => {
                for variant in variants {
                    for field in &variant.fields {
                        for dep in direct_named_deps(&field.ty) {
                            edges.entry(id.clone()).or_default().insert(dep);
                        }
                    }
                }
            }
            ProjectedShape::StringEnum { .. } | ProjectedShape::Const { .. } => {}
        }
    }

    let scc_of = deterministic_sccs(&edges);
    for (id, decl) in decls.iter_mut() {
        let owner_scc = scc_of.get(id).copied().unwrap_or(0);
        match &mut decl.shape {
            ProjectedShape::Object { fields, .. } => {
                for field in fields {
                    box_direct_scc_named(&mut field.ty, owner_scc, &scc_of);
                }
            }
            ProjectedShape::TaggedUnion { variants, .. } => {
                for variant in variants {
                    for field in &mut variant.fields {
                        box_direct_scc_named(&mut field.ty, owner_scc, &scc_of);
                    }
                }
            }
            ProjectedShape::StringEnum { .. } | ProjectedShape::Const { .. } => {}
        }
    }
    Ok(())
}

fn direct_named_deps(ty: &RustTypeExpr) -> Vec<RustDeclarationId> {
    match ty {
        RustTypeExpr::Named(id) => vec![id.clone()],
        RustTypeExpr::Nullable(inner) | RustTypeExpr::Boxed(inner) => direct_named_deps(inner),
        // Array is indirect ownership — no direct edge.
        RustTypeExpr::Array(_) => Vec::new(),
        RustTypeExpr::Scalar(_) | RustTypeExpr::AnyJson => Vec::new(),
    }
}

fn box_direct_scc_named(
    ty: &mut RustTypeExpr,
    owner_scc: usize,
    scc_of: &BTreeMap<RustDeclarationId, usize>,
) {
    match ty {
        RustTypeExpr::Named(id) => {
            if scc_of.get(id).copied() == Some(owner_scc) {
                let named = RustTypeExpr::Named(id.clone());
                *ty = RustTypeExpr::Boxed(Box::new(named));
            }
        }
        RustTypeExpr::Nullable(inner) | RustTypeExpr::Boxed(inner) => {
            box_direct_scc_named(inner, owner_scc, scc_of);
        }
        // Do not insert Box through Array indirection.
        RustTypeExpr::Array(_) => {}
        RustTypeExpr::Scalar(_) | RustTypeExpr::AnyJson => {}
    }
}

/// Deterministic Kosaraju SCC. Component ids are assigned in sorted-root order.
fn deterministic_sccs(
    edges: &BTreeMap<RustDeclarationId, BTreeSet<RustDeclarationId>>,
) -> BTreeMap<RustDeclarationId, usize> {
    let mut nodes: Vec<RustDeclarationId> = edges.keys().cloned().collect();
    nodes.sort();

    // First pass: order by finish time (iterative DFS, nodes visited in sorted order).
    let mut visited = BTreeSet::new();
    let mut order = Vec::new();
    for start in &nodes {
        if !visited.insert(start.clone()) {
            continue;
        }
        let mut stack = vec![(start.clone(), false)];
        while let Some((node, post)) = stack.pop() {
            if post {
                order.push(node);
                continue;
            }
            stack.push((node.clone(), true));
            if let Some(succs) = edges.get(&node) {
                let mut succ_list: Vec<_> = succs.iter().cloned().collect();
                succ_list.sort();
                // Push reverse so smallest is processed first.
                for succ in succ_list.into_iter().rev() {
                    if visited.insert(succ.clone()) {
                        stack.push((succ, false));
                    }
                }
            }
        }
    }

    // Transpose.
    let mut rev: BTreeMap<RustDeclarationId, BTreeSet<RustDeclarationId>> = BTreeMap::new();
    for node in &nodes {
        rev.entry(node.clone()).or_default();
    }
    for (from, tos) in edges {
        for to in tos {
            rev.entry(to.clone()).or_default().insert(from.clone());
        }
    }

    let mut scc_of = BTreeMap::new();
    let mut assigned = BTreeSet::new();
    let mut component_id = 0usize;
    for start in order.into_iter().rev() {
        if !assigned.insert(start.clone()) {
            continue;
        }
        let mut stack = vec![start.clone()];
        scc_of.insert(start.clone(), component_id);
        while let Some(node) = stack.pop() {
            if let Some(preds) = rev.get(&node) {
                let mut pred_list: Vec<_> = preds.iter().cloned().collect();
                pred_list.sort();
                for pred in pred_list {
                    if assigned.insert(pred.clone()) {
                        scc_of.insert(pred.clone(), component_id);
                        stack.push(pred);
                    }
                }
            }
        }
        component_id += 1;
    }
    scc_of
}

fn shape_is_named(shape: &TypeShape) -> bool {
    matches!(
        shape,
        TypeShape::Object { .. }
            | TypeShape::TaggedUnion { .. }
            | TypeShape::StringEnum { .. }
            | TypeShape::Const { .. }
    )
}

fn root_rust_name(node: &crate::contract_model::ContractTypeNode) -> String {
    if let Some(title) = &node.schema_title {
        if !title.is_empty() {
            return to_pascal_case(title);
        }
    }
    type_name_from_schema_id(&node.id.schema_id)
}

fn type_name_from_schema_id(id: &str) -> String {
    to_pascal_case(
        id.rsplit('/')
            .next()
            .unwrap_or(id)
            .trim_end_matches(".json"),
    )
}

fn audit_decl_internal_collisions(decl: &ProjectedDecl) -> Result<()> {
    match &decl.shape {
        ProjectedShape::Object { fields, .. } => {
            let mut rust_fields: BTreeMap<String, String> = BTreeMap::new();
            for field in fields {
                let rust_name = rust_field_name(&field.json_name);
                if let Some(previous) =
                    rust_fields.insert(rust_name.clone(), field.json_name.clone())
                {
                    return Err(SchemaToolError::msg(format!(
                        "Rust field name collision in `{}` ({}): json fields {previous:?} and {:?} both map to `{rust_name}` (use-sites /properties/{previous} and /properties/{})",
                        decl.rust_name,
                        decl.id.display(),
                        field.json_name,
                        field.json_name
                    ))
                    .into());
                }
            }
        }
        ProjectedShape::TaggedUnion { variants, .. } => {
            let mut names = BTreeMap::new();
            for variant in variants {
                if let Some(previous) = names.insert(variant.rust_name.clone(), variant.tag.clone())
                {
                    return Err(SchemaToolError::msg(format!(
                        "Rust tagged-union variant collision in `{}` ({}): tags {previous:?} (canonical {}, arm {}) and {:?} (canonical {}, arm {}) both map to `{}`",
                        decl.rust_name,
                        decl.id.display(),
                        variants
                            .iter()
                            .find(|candidate| candidate.tag == previous)
                            .map(|candidate| candidate.object_type_id.display())
                            .unwrap_or_else(|| "<missing canonical identity>".to_string()),
                        variants
                            .iter()
                            .find(|candidate| candidate.tag == previous)
                            .map(|candidate| candidate.source.display())
                            .unwrap_or_else(|| "<missing arm>".to_string()),
                        variant.tag,
                        variant.object_type_id.display(),
                        variant.source.display(),
                        variant.rust_name
                    ))
                    .into());
                }
                let mut fields = BTreeMap::new();
                for field in &variant.fields {
                    let rust_name = rust_field_name(&field.json_name);
                    if let Some(previous) =
                        fields.insert(rust_name.clone(), field.json_name.clone())
                    {
                        return Err(SchemaToolError::msg(format!(
                            "Rust tagged-union field collision in `{}` variant `{}`: json fields {previous:?} and {:?} both map to `{rust_name}`",
                            decl.rust_name, variant.rust_name, field.json_name
                        ))
                        .into());
                    }
                }
            }
        }
        ProjectedShape::StringEnum { values } => {
            let mut variants: BTreeMap<String, String> = BTreeMap::new();
            for value in values {
                let variant = rust_enum_variant(value);
                if let Some(previous) = variants.insert(variant.clone(), value.clone()) {
                    return Err(SchemaToolError::msg(format!(
                        "Rust enum variant collision in type `{}` ({}): wire values {previous:?} and {value:?} both map to variant `{variant}`",
                        decl.rust_name,
                        decl.id.display()
                    ))
                    .into());
                }
            }
        }
        ProjectedShape::Const { .. } => {}
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// Public render entry points (single-projection path only)
// ---------------------------------------------------------------------------

/// Render types from an already-computed [`RustProjection`].
///
/// Production and public API must call [`project_rust`] once and share that
/// projection with typed rendering; convenience re-project helpers are not public.
pub fn render_types_module_from_projection(projection: &RustProjection) -> Result<String> {
    let mut out = String::from(GENERATED_HEADER);
    out.push_str("\n#![cfg_attr(rustfmt, rustfmt::skip)]\n");
    out.push_str("#![allow(clippy::all)]\n#![allow(dead_code)]\n#![allow(unused_imports)]\n\n");
    out.push_str("use serde::{Deserialize, Deserializer, Serialize, Serializer};\n");
    out.push_str("use serde::de::Error as DeError;\n");
    out.push_str("use serde_json::Value as JsonValue;\n\n");
    out.push_str(render_null_only());
    out.push('\n');

    let mut string_enums: Vec<(String, Vec<String>)> = Vec::new();
    for decl in &projection.decls {
        if let ProjectedShape::StringEnum { values } = &decl.shape {
            string_enums.push((decl.rust_name.clone(), values.clone()));
        }
        let body = render_projected_decl(decl, &projection.names)?;
        out.push_str(&body);
        if !body.ends_with('\n') {
            out.push('\n');
        }
        out.push('\n');
    }
    out.push_str(&render_string_enum_contract_tests(&string_enums));
    Ok(out)
}

/// Render typed decode from an already-computed [`RustProjection`].
pub fn render_typed_module_from_projection(
    projection: &RustProjection,
    graph: &TargetContractGraph,
) -> Result<String> {
    let decl_by_id: BTreeMap<RustDeclarationId, &ProjectedDecl> =
        projection.decls.iter().map(|d| (d.id.clone(), d)).collect();

    let mut rendered = Vec::new();
    let mut imports = BTreeSet::new();
    for binding in &graph.envelopes {
        rendered.push(render_typed_envelope(
            binding,
            &projection.names,
            &projection.root_names,
            &decl_by_id,
            &mut imports,
        )?);
    }

    let mut out = String::from(GENERATED_HEADER);
    out.push_str("\n#![cfg_attr(rustfmt, rustfmt::skip)]\n");
    out.push_str("#![allow(clippy::all)]\n\n");
    out.push_str(
        "//! Typed envelope decoding derived from conditional JSON Schema payload mappings.\n\n",
    );
    out.push_str("use crate::error::ContractError;\n");
    out.push_str("use crate::validator::validate_json;\n");
    if !imports.is_empty() {
        out.push_str("use super::types::{\n");
        for name in imports {
            out.push_str(&format!("    {name},\n"));
        }
        out.push_str("};\n");
    }
    out.push_str("use serde::Deserialize;\n");
    out.push_str("use serde_json::Value;\n\n");
    for body in rendered {
        out.push_str(&body);
        if !body.ends_with('\n') {
            out.push('\n');
        }
        out.push('\n');
    }
    out.push_str(render_typed_decode_helpers());
    Ok(out)
}

pub fn render_catalog_module(graph: &TargetContractGraph) -> Result<String> {
    let mut out = String::from(GENERATED_HEADER);
    out.push_str("\n#![cfg_attr(rustfmt, rustfmt::skip)]\n\n");
    out.push_str("/// Embedded schema documents generated from schemas/manifest.json.\n");
    out.push_str("pub const EMBEDDED_SCHEMA_DOCUMENTS: &[(&str, &str)] = &[\n");
    for (id, source) in &graph.catalog.embedded_sources {
        let include_path = format!("../../../../../{source}");
        out.push_str(&format!(
            "    ({:?}, include_str!({:?})),\n",
            id, include_path
        ));
    }
    out.push_str("];\n\n");

    // Active catalogs: empty when V2 Envelope authority is absent (current production).
    render_str_slice(
        &mut out,
        "KCP_COMMAND_METHODS",
        &graph.catalog.kcp_command_methods,
    );
    render_str_slice(
        &mut out,
        "KCP_QUERY_METHODS",
        &graph.catalog.kcp_query_methods,
    );
    render_str_slice(&mut out, "KCP_METHODS", &graph.catalog.kcp_methods);

    // Explicit retained v1 catalogs. Not active authority; consumers that still need
    // the retained first-batch set must opt into LEGACY names.
    render_str_slice(
        &mut out,
        "KCP_LEGACY_V1_COMMAND_METHODS",
        &graph.catalog.kcp_legacy_v1_command_methods,
    );
    render_str_slice(
        &mut out,
        "KCP_LEGACY_V1_QUERY_METHODS",
        &graph.catalog.kcp_legacy_v1_query_methods,
    );
    render_str_slice(
        &mut out,
        "KCP_LEGACY_V1_METHODS",
        &graph.catalog.kcp_legacy_v1_methods,
    );

    render_str_slice(&mut out, "EVENT_V1_TYPES", &graph.catalog.event_v1_types);
    out.push_str(&format!(
        "pub const KCP_PROTOCOL_VERSION: &str = {:?};\n",
        graph.catalog.kcp_protocol_version
    ));

    render_method_version_bindings(&mut out, &graph.catalog.method_version_bindings)?;
    Ok(out)
}

fn render_method_version_bindings(
    out: &mut String,
    bindings: &[crate::method_bindings::MethodVersionBindingFact],
) -> Result<()> {
    out.push_str("\n/// Manifest-derived method version binding facts (library selectors only).\n");
    out.push_str(
        "/// Does not imply dispatcher registration, handler, repository, or server availability.\n",
    );
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub enum KcpMethodFamily {\n    Command,\n    Query,\n}\n\n");
    out.push_str("#[derive(Debug, Clone, PartialEq, Eq)]\n");
    out.push_str("pub struct MethodVersionBinding {\n");
    out.push_str("    pub family: KcpMethodFamily,\n");
    out.push_str("    pub method: &'static str,\n");
    out.push_str("    pub active_request_versions: &'static [u32],\n");
    out.push_str("    pub legacy_validation_versions: &'static [u32],\n");
    out.push_str("    pub request_schema_id_by_version: &'static [(u32, &'static str)],\n");
    out.push_str("    pub response_schema_id_by_version: &'static [(u32, &'static str)],\n");
    out.push_str("}\n\n");

    out.push_str("#[derive(Debug, Clone, PartialEq, Eq)]\n");
    out.push_str("pub enum RequestVersionSelection {\n");
    out.push_str(
        "    Active { request_schema_id: &'static str, response_schema_id: &'static str },\n",
    );
    out.push_str("    LegacyValidationOnly { request_schema_id: &'static str },\n");
    out.push_str("    Unsupported,\n");
    out.push_str("}\n\n");

    // Emit supporting consts first so the public table can reference them.
    for (index, binding) in bindings.iter().enumerate() {
        let active_name = format!("_METHOD_BINDING_{index}_ACTIVE");
        let legacy_name = format!("_METHOD_BINDING_{index}_LEGACY");
        let request_name = format!("_METHOD_BINDING_{index}_REQUEST_IDS");
        let response_name = format!("_METHOD_BINDING_{index}_RESPONSE_IDS");

        out.push_str(&format!(
            "const {active_name}: &[u32] = &{:?};\n",
            binding.active_request_versions
        ));
        out.push_str(&format!(
            "const {legacy_name}: &[u32] = &{:?};\n",
            binding.legacy_validation_versions
        ));
        out.push_str(&format!("const {request_name}: &[(u32, &str)] = &[\n"));
        for (key, id) in &binding.request_schema_id_by_version {
            let version: u32 = key
                .parse()
                .map_err(|_| SchemaToolError::msg(format!("invalid binding version key {key}")))?;
            out.push_str(&format!("    ({version}, {id:?}),\n"));
        }
        out.push_str("];\n");
        out.push_str(&format!("const {response_name}: &[(u32, &str)] = &[\n"));
        for (key, id) in &binding.response_schema_id_by_version {
            let version: u32 = key
                .parse()
                .map_err(|_| SchemaToolError::msg(format!("invalid binding version key {key}")))?;
            out.push_str(&format!("    ({version}, {id:?}),\n"));
        }
        out.push_str("];\n");
    }

    out.push_str("pub const METHOD_VERSION_BINDINGS: &[MethodVersionBinding] = &[\n");
    for (index, binding) in bindings.iter().enumerate() {
        let family = match binding.family {
            crate::manifest::MethodFamily::Command => "KcpMethodFamily::Command",
            crate::manifest::MethodFamily::Query => "KcpMethodFamily::Query",
        };
        let active_name = format!("_METHOD_BINDING_{index}_ACTIVE");
        let legacy_name = format!("_METHOD_BINDING_{index}_LEGACY");
        let request_name = format!("_METHOD_BINDING_{index}_REQUEST_IDS");
        let response_name = format!("_METHOD_BINDING_{index}_RESPONSE_IDS");
        out.push_str("    MethodVersionBinding {\n");
        out.push_str(&format!("        family: {family},\n"));
        out.push_str(&format!("        method: {:?},\n", binding.method));
        out.push_str(&format!(
            "        active_request_versions: {active_name},\n"
        ));
        out.push_str(&format!(
            "        legacy_validation_versions: {legacy_name},\n"
        ));
        out.push_str(&format!(
            "        request_schema_id_by_version: {request_name},\n"
        ));
        out.push_str(&format!(
            "        response_schema_id_by_version: {response_name},\n"
        ));
        out.push_str("    },\n");
    }
    out.push_str("];\n\n");

    out.push_str(render_binding_query_apis());
    Ok(())
}

fn render_binding_query_apis() -> &'static str {
    r#"/// Lookup a method version binding by family + method.
pub fn method_version_binding(
    family: KcpMethodFamily,
    method: &str,
) -> Option<&'static MethodVersionBinding> {
    METHOD_VERSION_BINDINGS
        .iter()
        .find(|binding| binding.family == family && binding.method == method)
}

/// Select the complete lifecycle outcome for one request version.
/// Active response selection is inseparable from the request version.
pub fn select_request_version(
    family: KcpMethodFamily,
    method: &str,
    request_version: u32,
) -> RequestVersionSelection {
    let Some(binding) = method_version_binding(family, method) else {
        return RequestVersionSelection::Unsupported;
    };
    let request_schema_id = binding
        .request_schema_id_by_version
        .iter()
        .find(|(version, _)| *version == request_version)
        .map(|(_, id)| *id);
    if binding.active_request_versions.contains(&request_version) {
        let response_schema_id = binding
            .response_schema_id_by_version
            .iter()
            .find(|(version, _)| *version == request_version)
            .map(|(_, id)| *id);
        return match (request_schema_id, response_schema_id) {
            (Some(request_schema_id), Some(response_schema_id)) => {
                RequestVersionSelection::Active {
                    request_schema_id,
                    response_schema_id,
                }
            }
            _ => RequestVersionSelection::Unsupported,
        };
    }
    if binding.legacy_validation_versions.contains(&request_version) {
        return request_schema_id
            .map(|request_schema_id| RequestVersionSelection::LegacyValidationOnly {
                request_schema_id,
            })
            .unwrap_or(RequestVersionSelection::Unsupported);
    }
    RequestVersionSelection::Unsupported
}
"#
}

// ---------------------------------------------------------------------------
// Declaration rendering
// ---------------------------------------------------------------------------

fn render_projected_decl(
    decl: &ProjectedDecl,
    names: &BTreeMap<RustDeclarationId, String>,
) -> Result<String> {
    match &decl.shape {
        ProjectedShape::Object {
            fields,
            unknown_field_policy,
        } => render_struct(
            &decl.rust_name,
            &decl.doc_schema_id,
            fields,
            *unknown_field_policy,
            names,
        ),
        ProjectedShape::TaggedUnion {
            discriminator,
            variants,
        } => render_tagged_union(
            &decl.rust_name,
            &decl.doc_schema_id,
            discriminator,
            variants,
            names,
        ),
        ProjectedShape::StringEnum { values } => Ok(render_string_enum(
            &decl.rust_name,
            &decl.doc_schema_id,
            values,
        )),
        ProjectedShape::Const { value } => Ok(render_const_type(
            &decl.rust_name,
            &decl.doc_schema_id,
            value,
        )),
    }
}

fn render_struct(
    type_name: &str,
    schema_id: &str,
    fields: &[ProjectedField],
    unknown_field_policy: UnknownFieldPolicy,
    names: &BTreeMap<RustDeclarationId, String>,
) -> Result<String> {
    let serde_attribute = match unknown_field_policy {
        UnknownFieldPolicy::Forbid => "\n#[serde(deny_unknown_fields)]",
        UnknownFieldPolicy::Allow => "",
    };
    let mut body = format!(
        "/// Generated from `{schema_id}`\n#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]{serde_attribute}\npub struct {type_name} {{\n"
    );
    for field in fields {
        let rust_name = rust_field_name(&field.json_name);
        let mut rendered = render_rust_type_expr(&field.ty, names, TypeRenderContext::TypesModule)?;
        if field.presence == Presence::Optional && !rendered.starts_with("Option<") {
            rendered = format!("Option<{rendered}>");
        }

        let mut serde_attrs = Vec::new();
        if rust_name != field.json_name {
            serde_attrs.push(format!("rename = {:?}", field.json_name));
        }
        if field.presence == Presence::Optional && field.nullability == Nullability::NonNull {
            serde_attrs.push("skip_serializing_if = \"Option::is_none\"".to_string());
        }
        if !serde_attrs.is_empty() {
            body.push_str(&format!("    #[serde({})]\n", serde_attrs.join(", ")));
        }
        body.push_str(&format!("    pub {rust_name}: {rendered},\n"));
    }
    body.push_str("}\n");
    Ok(body)
}

fn render_tagged_union(
    type_name: &str,
    schema_id: &str,
    discriminator: &str,
    variants: &[ProjectedVariant],
    names: &BTreeMap<RustDeclarationId, String>,
) -> Result<String> {
    let mut body = format!(
        "/// Generated internally tagged union from `{schema_id}`\n#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]\n#[serde(tag = {discriminator:?}, deny_unknown_fields)]\npub enum {type_name} {{\n"
    );
    for variant in variants {
        body.push_str(&format!(
            "    #[serde(rename = {:?})]\n    {} {{\n",
            variant.tag, variant.rust_name
        ));
        for field in &variant.fields {
            let rust_name = rust_field_name(&field.json_name);
            let mut rendered =
                render_rust_type_expr(&field.ty, names, TypeRenderContext::TypesModule)?;
            if field.presence == Presence::Optional && !rendered.starts_with("Option<") {
                rendered = format!("Option<{rendered}>");
            }
            let mut serde_attrs = Vec::new();
            if rust_name != field.json_name {
                serde_attrs.push(format!("rename = {:?}", field.json_name));
            }
            if field.presence == Presence::Optional && field.nullability == Nullability::NonNull {
                serde_attrs.push("skip_serializing_if = \"Option::is_none\"".to_string());
            }
            if !serde_attrs.is_empty() {
                body.push_str(&format!("        #[serde({})]\n", serde_attrs.join(", ")));
            }
            body.push_str(&format!("        {rust_name}: {rendered},\n"));
        }
        body.push_str("    },\n");
    }
    body.push_str("}\n");
    Ok(body)
}

#[derive(Clone, Copy)]
enum TypeRenderContext {
    TypesModule,
    TypedModule,
}

fn render_rust_type_expr(
    ty: &RustTypeExpr,
    names: &BTreeMap<RustDeclarationId, String>,
    ctx: TypeRenderContext,
) -> Result<String> {
    match ty {
        RustTypeExpr::Scalar(scalar) => Ok(match scalar {
            ScalarKind::Null => "NullOnly".into(),
            ScalarKind::Boolean => "bool".into(),
            ScalarKind::Integer => "i64".into(),
            ScalarKind::Number => "f64".into(),
            ScalarKind::String => "String".into(),
        }),
        RustTypeExpr::AnyJson => Ok(match ctx {
            TypeRenderContext::TypesModule => "JsonValue".into(),
            TypeRenderContext::TypedModule => "Value".into(),
        }),
        RustTypeExpr::Array(items) => Ok(format!(
            "Vec<{}>",
            render_rust_type_expr(items, names, ctx)?
        )),
        RustTypeExpr::Nullable(inner) => {
            let rendered = render_rust_type_expr(inner, names, ctx)?;
            if rendered.starts_with("Option<") {
                Ok(rendered)
            } else {
                Ok(format!("Option<{rendered}>"))
            }
        }
        RustTypeExpr::Boxed(inner) => Ok(format!(
            "Box<{}>",
            render_rust_type_expr(inner, names, ctx)?
        )),
        RustTypeExpr::Named(id) => names.get(id).cloned().ok_or_else(|| {
            SchemaToolError::msg(format!(
                "internal renderer error: missing Rust symbol for {}",
                id.display()
            ))
            .into()
        }),
    }
}

fn render_const_type(name: &str, schema_id: &str, value: &ConstJson) -> String {
    match value {
        ConstJson::String { value: expected } => format!(
            "/// Generated string const from `{schema_id}`\n#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]\npub enum {name} {{\n    #[serde(rename = {:?})]\n    Value,\n}}\n",
            expected
        ),
        ConstJson::Integer { value: expected } => format!(
            "/// Generated integer const from `{schema_id}`\n#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]\npub struct {name};\nimpl Serialize for {name} {{ fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error> where S: Serializer {{ serializer.serialize_i64({expected}) }} }}\nimpl<'de> Deserialize<'de> for {name} {{ fn deserialize<D>(deserializer: D) -> Result<Self, D::Error> where D: Deserializer<'de> {{ let value = i64::deserialize(deserializer)?; if value == {expected} {{ Ok(Self) }} else {{ Err(D::Error::custom(format!(\"expected integer const {expected}, got {{value}}\"))) }} }} }}\n"
        ),
        ConstJson::UnsignedInteger { value: expected } => format!(
            "/// Generated integer const from `{schema_id}`\n#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]\npub struct {name};\nimpl Serialize for {name} {{ fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error> where S: Serializer {{ serializer.serialize_u64({expected}) }} }}\nimpl<'de> Deserialize<'de> for {name} {{ fn deserialize<D>(deserializer: D) -> Result<Self, D::Error> where D: Deserializer<'de> {{ let value = u64::deserialize(deserializer)?; if value == {expected} {{ Ok(Self) }} else {{ Err(D::Error::custom(format!(\"expected integer const {expected}, got {{value}}\"))) }} }} }}\n"
        ),
        ConstJson::Bool { value: expected } => format!(
            "/// Generated boolean const from `{schema_id}`\n#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]\npub struct {name};\nimpl Serialize for {name} {{ fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error> where S: Serializer {{ serializer.serialize_bool({expected}) }} }}\nimpl<'de> Deserialize<'de> for {name} {{ fn deserialize<D>(deserializer: D) -> Result<Self, D::Error> where D: Deserializer<'de> {{ let value = bool::deserialize(deserializer)?; if value == {expected} {{ Ok(Self) }} else {{ Err(D::Error::custom(format!(\"expected boolean const {expected}, got {{value}}\"))) }} }} }}\n"
        ),
        ConstJson::Null => render_null_only().replace("NullOnly", name),
    }
}

fn render_string_enum(type_name: &str, schema_id: &str, values: &[String]) -> String {
    // One ordered mapping drives variants, ALL, and as_str so declaration order is shared.
    let mapping: Vec<(&str, String)> = values
        .iter()
        .map(|value| (value.as_str(), rust_enum_variant(value)))
        .collect();

    let mut body = format!(
        "/// Generated string enum from `{schema_id}`\n#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]\npub enum {type_name} {{\n"
    );
    for (wire, variant) in &mapping {
        body.push_str(&format!(
            "    #[serde(rename = {wire:?})]\n    {variant},\n"
        ));
    }
    body.push_str("}\n");

    body.push_str(&format!("\nimpl {type_name} {{\n"));
    body.push_str(
        "    /// Schema enum declaration-order closed set (null filtered at use-site Option).\n",
    );
    body.push_str("    pub const ALL: &'static [Self] = &[\n");
    for (_, variant) in &mapping {
        body.push_str(&format!("        Self::{variant},\n"));
    }
    body.push_str("    ];\n\n");
    body.push_str("    pub fn as_str(self) -> &'static str {\n        match self {\n");
    for (wire, variant) in &mapping {
        body.push_str(&format!("            Self::{variant} => {wire:?},\n"));
    }
    body.push_str("        }\n    }\n}\n");
    body
}

/// Auto-generated contract tests covering every projected string enum.
///
/// Shared helper avoids per-enum boilerplate; projection emits one call site each.
fn render_string_enum_contract_tests(enums: &[(String, Vec<String>)]) -> String {
    if enums.is_empty() {
        return String::new();
    }

    let mut out = String::from(
        "#[cfg(test)]\nmod string_enum_contracts {\n    use super::*;\n    use serde_json::Value;\n    use std::collections::BTreeSet;\n\n",
    );
    out.push_str(
        "    fn assert_string_enum_contract<T, F>(\n        all: &'static [T],\n        expected_wires: &[&str],\n        as_str: F,\n    ) where\n        T: Copy + PartialEq + std::fmt::Debug + Serialize + for<'de> Deserialize<'de>,\n        F: Fn(T) -> &'static str,\n    {\n        assert_eq!(\n            all.len(),\n            expected_wires.len(),\n            \"ALL length must match schema enum declaration order\"\n        );\n        let mut seen = BTreeSet::new();\n        for (index, member) in all.iter().copied().enumerate() {\n            let wire = as_str(member);\n            assert_eq!(\n                wire,\n                expected_wires[index],\n                \"ALL/as_str order must follow schema declaration\"\n            );\n            assert!(seen.insert(wire), \"as_str wire must be unique: {wire}\");\n            let value = serde_json::to_value(member).expect(\"serialize string enum\");\n            assert_eq!(value, Value::String(wire.to_owned()));\n            let roundtrip: T =\n                serde_json::from_value(value).expect(\"deserialize string enum\");\n            assert_eq!(roundtrip, member);\n        }\n    }\n\n",
    );

    for (type_name, values) in enums {
        let test_fn = format!("{}_string_enum_contract", to_snake_case(type_name));
        out.push_str(&format!("    #[test]\n    fn {test_fn}() {{\n"));
        out.push_str(&format!(
            "        assert_string_enum_contract(\n            {type_name}::ALL,\n            &[\n"
        ));
        for value in values {
            out.push_str(&format!("                {value:?},\n"));
        }
        out.push_str(&format!(
            "            ],\n            {type_name}::as_str,\n        );\n    }}\n\n"
        ));
    }
    out.push_str("}\n");
    out
}

fn render_null_only() -> &'static str {
    "/// JSON null and no other value.\n#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]\npub struct NullOnly;\nimpl Serialize for NullOnly { fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error> where S: Serializer { serializer.serialize_none() } }\nimpl<'de> Deserialize<'de> for NullOnly { fn deserialize<D>(deserializer: D) -> Result<Self, D::Error> where D: Deserializer<'de> { <()>::deserialize(deserializer).map(|()| Self) } }\n"
}

fn render_str_slice(out: &mut String, name: &str, values: &[String]) {
    out.push_str(&format!("pub const {name}: &[&str] = &[\n"));
    for value in values {
        out.push_str(&format!("    {:?},\n", value));
    }
    out.push_str("];\n\n");
}

// ---------------------------------------------------------------------------
// Typed envelope rendering (reuses graph root object fields)
// ---------------------------------------------------------------------------

fn render_typed_envelope(
    binding: &EnvelopeWireBinding,
    names: &BTreeMap<RustDeclarationId, String>,
    root_name: &BTreeMap<String, String>,
    decl_by_id: &BTreeMap<RustDeclarationId, &ProjectedDecl>,
    imports: &mut BTreeSet<String>,
) -> Result<String> {
    let base_name = typed_envelope_base_name(&binding.schema_title);
    let api_prefix = if binding.schema_title.starts_with("Kcp") {
        "Kcp"
    } else {
        ""
    };
    let payload_enum_name = format!("{api_prefix}{base_name}Payload");
    let typed_name = format!("Typed{api_prefix}{base_name}Envelope");
    let raw_name = format!("Raw{api_prefix}{base_name}Envelope");
    let schema_const_name = format!("{}_SCHEMA_ID", to_upper_snake_case(&binding.schema_title));

    let mut variant_to_value: BTreeMap<String, String> = BTreeMap::new();
    let mut mappings_rendered = Vec::new();
    for mapping in &binding.mappings {
        let variant_name = to_pascal_case(&mapping.discriminator_value);
        if let Some(previous) =
            variant_to_value.insert(variant_name.clone(), mapping.discriminator_value.clone())
        {
            return Err(SchemaToolError::msg(format!(
                "conditional payload mapping error in {}: Rust variant collision: discriminator values {previous:?} and {:?} both map to {variant_name}",
                binding.schema_id, mapping.discriminator_value
            ))
            .into());
        }
        let payload_type = root_name
            .get(&mapping.payload_type.schema_id)
            .cloned()
            .ok_or_else(|| {
                SchemaToolError::msg(format!(
                    "internal renderer error: missing payload type for {}",
                    mapping.payload_type.display()
                ))
            })?;
        imports.insert(payload_type.clone());
        mappings_rendered.push((
            mapping.discriminator_value.clone(),
            variant_name,
            payload_type,
        ));
    }

    // Consume the same projected layout as types.rs (no parallel envelope projection).
    let root_decl_id = RustDeclarationId::SharedRoot {
        schema_id: binding.schema_id.clone(),
    };
    let root_decl = decl_by_id.get(&root_decl_id).ok_or_else(|| {
        SchemaToolError::msg(format!(
            "internal renderer error: missing projected envelope root for {}",
            binding.schema_id
        ))
    })?;
    let ProjectedShape::Object { fields, .. } = &root_decl.shape else {
        return Err(SchemaToolError::msg(format!(
            "internal renderer error: envelope root is not an object projection: {}",
            binding.schema_id
        ))
        .into());
    };

    let mut ordered_fields: Vec<&ProjectedField> = fields.iter().collect();
    ordered_fields.sort_by(|a, b| a.json_name.cmp(&b.json_name));

    let mut raw_fields = Vec::new();
    let mut public_fields = Vec::new();
    let mut assignments = Vec::new();
    for field in ordered_fields {
        let json_name = &field.json_name;
        if json_name == &binding.discriminator {
            raw_fields.push(render_wire_field(json_name, "String", true));
            continue;
        }
        if json_name == "payload" {
            raw_fields.push(render_wire_field(json_name, "Value", true));
            continue;
        }
        let mut rust_type =
            render_rust_type_expr(&field.ty, names, TypeRenderContext::TypedModule)?;
        if field.presence == Presence::Optional && !rust_type.starts_with("Option<") {
            rust_type = format!("Option<{rust_type}>");
        }
        collect_named_type_imports(&rust_type, imports);
        raw_fields.push(render_wire_field(json_name, &rust_type, true));
        public_fields.push(render_wire_field(json_name, &rust_type, false));
        let field_rust = rust_field_name(json_name);
        assignments.push(format!("            {field_rust}: raw.{field_rust},\n"));
    }

    let mut out = String::new();
    out.push_str(&format!(
        "pub const {schema_const_name}: &str = {:?};\n\n",
        binding.schema_id
    ));
    out.push_str(&format!(
        "#[derive(Debug, Clone, PartialEq)]\npub struct {typed_name} {{\n"
    ));
    for field in &public_fields {
        out.push_str(field);
    }
    out.push_str(&format!(
        "    pub {}: String,\n",
        rust_field_name(&binding.discriminator)
    ));
    out.push_str(&format!("    pub payload: {payload_enum_name},\n}}\n\n"));

    out.push_str(&format!(
        "#[derive(Debug, Clone, PartialEq)]\npub enum {payload_enum_name} {{\n"
    ));
    for (_, variant_name, payload_type) in &mappings_rendered {
        out.push_str(&format!("    {variant_name}(Box<{payload_type}>),\n"));
    }
    out.push_str("}\n\n");

    out.push_str(&format!(
        "#[derive(Debug, Deserialize)]\n#[serde(deny_unknown_fields)]\nstruct {raw_name} {{\n"
    ));
    for field in &raw_fields {
        out.push_str(field);
    }
    out.push_str("}\n\n");

    let discriminator_field = rust_field_name(&binding.discriminator);
    out.push_str(&format!(
        "impl {typed_name} {{\n    pub fn decode(value: Value) -> Result<Self, ContractError> {{\n"
    ));
    out.push_str(&format!(
        "        validate_json({schema_const_name}, &value)?;\n        Self::decode_after_validation(value)\n    }}\n\n    /// Decodes a value that has already passed this envelope's generated Schema.\n    ///\n    /// Callers must validate with the matching envelope Schema before using this method.\n    pub fn decode_after_validation(value: Value) -> Result<Self, ContractError> {{\n"
    ));
    out.push_str(&format!(
        "        let raw: {raw_name} = deserialize_wire({schema_const_name}, value)?;\n"
    ));
    out.push_str(&format!(
        "        let discriminator = raw.{discriminator_field};\n"
    ));
    out.push_str("        let payload = match discriminator.as_str() {\n");
    for (disc_value, variant_name, _) in &mappings_rendered {
        out.push_str(&format!(
            "            {disc_value:?} => {payload_enum_name}::{variant_name}(Box::new(deserialize_payload({schema_const_name}, {disc_value:?}, raw.payload)?)),\n"
        ));
    }
    out.push_str(&format!("            value => return Err(ContractError::GeneratedDiscriminatorMapping {{ schema_id: {schema_const_name}.to_string(), discriminator: value.to_string() }}),\n"));
    out.push_str("        };\n        Ok(Self {\n");
    for assignment in assignments {
        out.push_str(&assignment);
    }
    out.push_str(&format!(
        "            {discriminator_field}: discriminator,\n            payload,\n        }})\n    }}\n}}\n"
    ));
    Ok(out)
}

fn render_wire_field(json_name: &str, rust_type: &str, private: bool) -> String {
    let rust_name = rust_field_name(json_name);
    let mut out = String::new();
    if rust_name != json_name {
        out.push_str(&format!("    #[serde(rename = {:?})]\n", json_name));
    }
    let visibility = if private { "" } else { "pub " };
    out.push_str(&format!("    {visibility}{rust_name}: {rust_type},\n"));
    out
}

fn collect_named_type_imports(rust_type: &str, imports: &mut BTreeSet<String>) {
    for token in rust_type.split(|ch: char| !ch.is_ascii_alphanumeric() && ch != '_') {
        if token
            .chars()
            .next()
            .is_some_and(|first| first.is_ascii_uppercase())
            && !matches!(token, "Option" | "String" | "Value" | "Box" | "Vec")
        {
            imports.insert(token.to_string());
        }
    }
}

fn typed_envelope_base_name(title: &str) -> String {
    let name = to_pascal_case(title);
    let without_prefix = name.strip_prefix("Kcp").unwrap_or(&name);
    without_prefix
        .strip_suffix("Envelope")
        .unwrap_or(without_prefix)
        .to_string()
}

fn render_typed_decode_helpers() -> &'static str {
    "fn deserialize_wire<T>(schema_id: &str, value: Value) -> Result<T, ContractError>\nwhere\n    T: for<'de> Deserialize<'de>,\n{\n    serde_json::from_value(value).map_err(|error| ContractError::WireDecodeAfterSchema {\n        schema_id: schema_id.to_string(),\n        detail: error.to_string(),\n    })\n}\n\nfn deserialize_payload<T>(\n    schema_id: &str,\n    discriminator: &str,\n    value: Value,\n) -> Result<T, ContractError>\nwhere\n    T: for<'de> Deserialize<'de>,\n{\n    serde_json::from_value(value).map_err(|error| ContractError::PayloadDecodeAfterSchema {\n        schema_id: schema_id.to_string(),\n        discriminator: discriminator.to_string(),\n        detail: error.to_string(),\n    })\n}\n"
}

// ---------------------------------------------------------------------------
// Rust naming policy (renderer exclusive)
// ---------------------------------------------------------------------------

fn rust_field_name(json_name: &str) -> String {
    let value = to_snake_case(json_name);
    if is_rust_keyword(&value) {
        format!("{value}_")
    } else {
        value
    }
}

fn rust_enum_variant(value: &str) -> String {
    if value.len() == 2 && value.starts_with('S') && value.as_bytes()[1].is_ascii_digit() {
        value.into()
    } else {
        to_pascal_case(value)
    }
}

fn is_rust_keyword(value: &str) -> bool {
    matches!(
        value,
        "as" | "async"
            | "await"
            | "break"
            | "const"
            | "continue"
            | "crate"
            | "dyn"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "fn"
            | "for"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "Self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "type"
            | "unsafe"
            | "use"
            | "where"
            | "while"
    )
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::contract_model::{
        CatalogFacts, ContractTypeNode, SourceSchemaMetadata, SourceUseSite, TypeShape,
    };
    use crate::json_pointer::JsonPointer;

    #[test]
    fn rust_keyword_field_gets_trailing_underscore() {
        assert_eq!(rust_field_name("type"), "type_");
        assert_eq!(rust_field_name("schema_version"), "schema_version");
    }

    #[test]
    fn symbol_collision_lists_both_identities() {
        let mut nodes = BTreeMap::new();
        let a = ContractTypeId::root("https://example/a.json");
        let b = ContractTypeId::root("https://example/b.json");
        nodes.insert(
            a.clone(),
            ContractTypeNode {
                id: a.clone(),
                schema_title: Some("SameName".into()),
                source: SourceSchemaMetadata::from_type_id(&a),
                shape: TypeShape::StringEnum {
                    values: vec!["x".into()],
                },
            },
        );
        nodes.insert(
            b.clone(),
            ContractTypeNode {
                id: b.clone(),
                schema_title: Some("SameName".into()),
                source: SourceSchemaMetadata::from_type_id(&b),
                shape: TypeShape::StringEnum {
                    values: vec!["y".into()],
                },
            },
        );
        let graph = TargetContractGraph {
            target: crate::manifest::GenerationTarget::Rust,
            source_schema_ids: vec![
                "https://example/a.json".into(),
                "https://example/b.json".into(),
            ],
            nodes,
            envelopes: vec![],
            catalog: CatalogFacts {
                embedded_sources: vec![],
                kcp_command_methods: vec![],
                kcp_query_methods: vec![],
                kcp_methods: vec![],
                kcp_legacy_v1_command_methods: vec![],
                kcp_legacy_v1_query_methods: vec![],
                kcp_legacy_v1_methods: vec![],
                event_v1_types: vec![],
                method_version_bindings: vec![],
                kcp_protocol_version: "1.0".into(),
            },
        };
        let err = Projector::new(&graph)
            .project_all()
            .unwrap_err()
            .to_string();
        assert!(err.contains("Rust type name collision"), "{err}");
        assert!(err.contains("https://example/a.json"), "{err}");
        assert!(err.contains("https://example/b.json"), "{err}");
    }

    #[test]
    fn nested_property_path_collision_fails_with_identities() {
        // Two properties that PascalCase to the same lineage under one root.
        let root = ContractTypeId::root("https://example/n.json");
        let status = root.child("properties").child("status");
        let status_cap = root.child("properties").child("Status");
        let mut nodes = BTreeMap::new();
        nodes.insert(
            root.clone(),
            ContractTypeNode {
                id: root.clone(),
                schema_title: Some("NestedHintCollision".into()),
                source: SourceSchemaMetadata::from_type_id(&root),
                shape: TypeShape::Object {
                    fields: vec![
                        crate::contract_model::ObjectField {
                            json_name: "status".into(),
                            ty: TypeUse {
                                expr: TypeExpr::Reference { id: status.clone() },
                                source: SourceUseSite::new(
                                    root.schema_id.clone(),
                                    status.pointer.clone(),
                                ),
                            },
                            presence: Presence::Required,
                            nullability: Nullability::NonNull,
                            schema_location: status.clone(),
                        },
                        crate::contract_model::ObjectField {
                            json_name: "Status".into(),
                            ty: TypeUse {
                                expr: TypeExpr::Reference {
                                    id: status_cap.clone(),
                                },
                                source: SourceUseSite::new(
                                    root.schema_id.clone(),
                                    status_cap.pointer.clone(),
                                ),
                            },
                            presence: Presence::Required,
                            nullability: Nullability::NonNull,
                            schema_location: status_cap.clone(),
                        },
                    ],
                    unknown_field_policy: UnknownFieldPolicy::Forbid,
                },
            },
        );
        nodes.insert(
            status.clone(),
            ContractTypeNode {
                id: status.clone(),
                schema_title: None,
                source: SourceSchemaMetadata::from_type_id(&status),
                shape: TypeShape::StringEnum {
                    values: vec!["a".into(), "b".into()],
                },
            },
        );
        nodes.insert(
            status_cap.clone(),
            ContractTypeNode {
                id: status_cap.clone(),
                schema_title: None,
                source: SourceSchemaMetadata::from_type_id(&status_cap),
                shape: TypeShape::StringEnum {
                    values: vec!["c".into(), "d".into()],
                },
            },
        );
        let graph = TargetContractGraph {
            target: crate::manifest::GenerationTarget::Rust,
            source_schema_ids: vec![root.schema_id.clone()],
            nodes,
            envelopes: vec![],
            catalog: CatalogFacts {
                embedded_sources: vec![],
                kcp_command_methods: vec![],
                kcp_query_methods: vec![],
                kcp_methods: vec![],
                kcp_legacy_v1_command_methods: vec![],
                kcp_legacy_v1_query_methods: vec![],
                kcp_legacy_v1_methods: vec![],
                event_v1_types: vec![],
                method_version_bindings: vec![],
                kcp_protocol_version: "1.0".into(),
            },
        };
        let err = Projector::new(&graph)
            .project_all()
            .unwrap_err()
            .to_string();
        assert!(err.contains("collision"), "{err}");
        assert!(
            err.contains("/properties/status")
                || err.contains("/properties/Status")
                || err.contains("NestedHintCollisionStatus")
                || (err.contains("status") && err.contains("Status")),
            "{err}"
        );
    }

    #[test]
    fn shared_defs_projects_two_clones() {
        let root = ContractTypeId::root("https://example/policy.json");
        let defs = root.child("$defs").child("actorEntryPoint");
        let created = root.child("properties").child("created_by");
        let updated = root.child("properties").child("updated_by");
        let mut nodes = BTreeMap::new();
        nodes.insert(
            root.clone(),
            ContractTypeNode {
                id: root.clone(),
                schema_title: Some("PolicyRule".into()),
                source: SourceSchemaMetadata::from_type_id(&root),
                shape: TypeShape::Object {
                    fields: vec![
                        crate::contract_model::ObjectField {
                            json_name: "created_by".into(),
                            ty: TypeUse {
                                expr: TypeExpr::Reference { id: defs.clone() },
                                source: SourceUseSite::new(
                                    root.schema_id.clone(),
                                    created.pointer.clone(),
                                ),
                            },
                            presence: Presence::Required,
                            nullability: Nullability::NonNull,
                            schema_location: created,
                        },
                        crate::contract_model::ObjectField {
                            json_name: "updated_by".into(),
                            ty: TypeUse {
                                expr: TypeExpr::Reference { id: defs.clone() },
                                source: SourceUseSite::new(
                                    root.schema_id.clone(),
                                    updated.pointer.clone(),
                                ),
                            },
                            presence: Presence::Required,
                            nullability: Nullability::NonNull,
                            schema_location: updated,
                        },
                    ],
                    unknown_field_policy: UnknownFieldPolicy::Forbid,
                },
            },
        );
        nodes.insert(
            defs.clone(),
            ContractTypeNode {
                id: defs.clone(),
                schema_title: None,
                source: SourceSchemaMetadata::from_type_id(&defs),
                shape: TypeShape::Object {
                    fields: vec![crate::contract_model::ObjectField {
                        json_name: "actor".into(),
                        ty: TypeUse {
                            expr: TypeExpr::Scalar {
                                scalar: ScalarKind::String,
                            },
                            source: SourceUseSite::new(
                                root.schema_id.clone(),
                                defs.pointer.child("properties").child("actor"),
                            ),
                        },
                        presence: Presence::Required,
                        nullability: Nullability::NonNull,
                        schema_location: defs.child("properties").child("actor"),
                    }],
                    unknown_field_policy: UnknownFieldPolicy::Forbid,
                },
            },
        );
        let graph = TargetContractGraph {
            target: crate::manifest::GenerationTarget::Rust,
            source_schema_ids: vec![root.schema_id.clone()],
            nodes,
            envelopes: vec![],
            catalog: CatalogFacts {
                embedded_sources: vec![],
                kcp_command_methods: vec![],
                kcp_query_methods: vec![],
                kcp_methods: vec![],
                kcp_legacy_v1_command_methods: vec![],
                kcp_legacy_v1_query_methods: vec![],
                kcp_legacy_v1_methods: vec![],
                event_v1_types: vec![],
                method_version_bindings: vec![],
                kcp_protocol_version: "1.0".into(),
            },
        };
        let decls = Projector::new(&graph).project_all().unwrap();
        let names: BTreeSet<_> = decls.iter().map(|d| d.rust_name.as_str()).collect();
        assert!(names.contains("PolicyRule"));
        assert!(names.contains("PolicyRuleCreatedBy"));
        assert!(names.contains("PolicyRuleUpdatedBy"));
        // Single canonical node, two declarations.
        let clones: Vec<_> = decls
            .iter()
            .filter(|d| {
                matches!(
                    &d.id,
                    RustDeclarationId::NominalInstantiation { canonical, .. } if canonical == &defs
                )
            })
            .collect();
        assert_eq!(clones.len(), 2);
    }

    #[test]
    fn renderer_source_does_not_walk_schema_shape() {
        let src = include_str!("rust_codegen.rs");
        let production = src
            .split("#[cfg(test)]")
            .next()
            .expect("production source before tests");
        let import_section = production.lines().take_while(|line| {
            let trimmed = line.trim();
            trimmed.is_empty()
                || trimmed.starts_with("//")
                || trimmed.starts_with("use ")
                || trimmed.starts_with("#![")
                || trimmed.starts_with("#[")
        });
        let imports: String = import_section.collect::<Vec<_>>().join("\n");
        assert!(!imports.contains("use crate::resolve"));
        assert!(!imports.contains("use serde_json"));
        assert!(!imports.contains("LoadedSchema"));
        for banned in [
            "schema_allows_null",
            "validate_supported_schema_node",
            "ensure_ref_has_only_annotation_siblings",
            "audit_schema_tree",
            "is_string_enum(",
            "is_object_schema(",
            "pointer_get(",
            "registry.get(",
            "document.pointer(",
        ] {
            assert!(
                !production.contains(banned),
                "renderer must not walk schema via {banned}"
            );
        }
        let _ = JsonPointer::root();
    }
}
